### ISSUE TITLE
Debian 7 Build Issue

### ISSUE THREAD

**Issue by ApfelUser** [middleman/middleman#1442] opened 2015-02-05 14:43 UTC
Hi, I am getting this error when trying to build my project:

```
middleman build
/usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require': cannot load such file -- ejs (LoadError)
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt/template.rb:144:in `require_template_library'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/sprockets-2.12.3/lib/sprockets/ejs_template.rb:20:in `initialize_engine'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt/template.rb:56:in `initialize'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt.rb:98:in `new'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt.rb:98:in `block in []'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt.rb:96:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/tilt-1.4.1/lib/tilt.rb:96:in `[]'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:245:in `remove_templating_extensions'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:197:in `extensionless_path'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/store.rb:189:in `file_to_path'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/extensions/on_disk.rb:41:in `touch_file'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/sitemap/extensions/on_disk.rb:20:in `block in initialize'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:173:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:173:in `block in run_callbacks'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:171:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:171:in `run_callbacks'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:101:in `did_change'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:133:in `block (2 levels) in reload_path'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:129:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:129:in `block in reload_path'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:122:in `chdir'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:122:in `reload_path'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/file_watcher.rb:45:in `block in registered'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/uber-0.0.11/lib/uber/options.rb:80:in `instance_exec'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/uber-0.0.11/lib/uber/options.rb:80:in `proc!'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/uber-0.0.11/lib/uber/options.rb:69:in `evaluate_for'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/uber-0.0.11/lib/uber/options.rb:60:in `evaluate'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/hook.rb:53:in `execute_callback'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/hook.rb:40:in `block in run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `each'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `inject'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/hook.rb:39:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks.rb:55:in `run_hook_for'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/hooks-0.4.0/lib/hooks/instance_hooks.rb:6:in `run_hook'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/core_extensions/request.rb:50:in `inst'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/cli/build.rb:95:in `shared_instance'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/cli/build.rb:62:in `build'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:72:in `method_missing'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:20:in `start'
        from /usr/local/rvm/gems/ruby-2.1.5/gems/middleman-core-3.3.7/bin/middleman:18:in `<top (required)>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/middleman:23:in `load'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/middleman:23:in `<main>'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

I am on:

*  Debian 3.2.65-1+deb7u1 x86_64 (Debian 7 Wheezy)
*  64 Bit
*  Gem 2.4.5
*  Ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-linux]

My Gems:

```
  * activesupport (4.1.8)
  * bundler (1.7.8)
  * celluloid (0.16.0)
  * chunky_png (1.3.3)
  * coffee-script (2.3.0)
  * coffee-script-source (1.8.0)
  * compass (1.0.1)
  * compass-core (1.0.1)
  * compass-import-once (1.0.5)
  * em-websocket (0.5.1)
  * erubis (2.7.0)
  * eventmachine (1.0.3)
  * execjs (2.2.2)
  * ffi (1.9.6)
  * haml (4.0.6)
  * hike (1.2.3)
  * hitimes (1.2.2)
  * hooks (0.4.0)
  * htmlcompressor (0.1.2)
  * http_parser.rb (0.6.0)
  * i18n (0.6.11)
  * json (1.8.1)
  * kramdown (1.5.0)
  * listen (2.8.3)
  * middleman (3.3.7)
  * middleman-core (3.3.7)
  * middleman-deploy (1.0.0)
  * middleman-livereload (3.1.1)
  * middleman-minify-html (3.4.0)
  * middleman-sprockets (3.3.10)
  * minitest (5.4.3)
  * multi_json (1.10.1)
  * net-sftp (2.1.2)
  * net-ssh (2.9.1)
  * padrino-helpers (0.12.4)
  * padrino-support (0.12.4)
  * ptools (1.3.1)
  * rack (1.5.2)
  * rack-livereload (0.3.15)
  * rack-test (0.6.2)
  * rb-fsevent (0.9.4)
  * rb-inotify (0.9.5)
  * sass (3.4.9)
  * sprockets (2.12.3)
  * sprockets-helpers (1.1.0)
  * sprockets-sass (1.2.0)
  * thor (0.19.1)
  * thread_safe (0.3.4)
  * tilt (1.4.1)
  * timers (4.0.1)
  * tzinfo (1.2.2)
  * uber (0.0.11)
  * uglifier (2.6.0)
```

**Comment by Arcovion** [comment] 2015-02-05 14:58
Duplicate of #1373
You must run Middleman through Bundler: `middleman build` &rarr; `bundle exec middleman build`

**Comment by ApfelUser** [comment] 2015-02-05 15:19
Hello, I already tried that and it is throwing the same error

**Comment by Arcovion** [comment] 2015-02-05 15:51
Is your site working with `middleman [server]` or is it just a problem with `middleman build`?
Can you upload a minimal project that reproduces the error, does it happen on a blank site created with `middleman init`?

**Comment by ApfelUser** [comment] 2015-02-05 16:34
It seems like there are some problematic files in my source folder. Is there a way to exclude folders from build so I can find out which file it is?

**Comment by tdreyno** [comment] 2015-02-05 17:49
Maybe add `ejs` gem to Gemfile?

**Comment by ApfelUser** [comment] 2015-02-05 18:08
@tdreyno :+1: Thanks, that does make it work a bit more actually! But I am now getting errors because of a Ruby Project inside my source folder. And I also don't want them to be processed by Middleman. So is there a way to exclude folders?

**Comment by Arcovion** [comment] 2015-02-05 19:20
Try:
```ruby
ignore 'path/to/dir/*'
```
Sounds like the same problem as https://github.com/middleman/middleman/pull/691#issuecomment-11511088

**Comment by tdreyno** [comment] 2015-02-05 19:20
I'm going to suggest you don't put non-source into `source`

**Comment by ApfelUser** [comment] 2015-02-11 21:21
@Arcovion :+1: Thanks! `ignore path/to/dir/*` does work! Closing

**Closed** 2015-03-23 17:36 UTC
