### ISSUE TITLE
error when opening config.rb

### ISSUE THREAD

**Issue by lbischof** [middleman/middleman#1736] opened 2016-01-06 17:22 UTC
I get this error when editing helpers (empty class):

```
E, [2016-01-06T18:19:11.098648 #23537] ERROR -- : run() in thread failed: stream closed:\n /home/lorenz/.rvm/gems/ruby-2.2.3/gems/rb-inotify-0.9.5/lib/rb-inotify/notif
ier.rb:295:in `readpartial'
```

What am I doing wrong?

**Comment by tdreyno** [comment] 2016-01-06 21:27
Not sure. Does the same thing happen when editing `config.rb`?

**Comment by lbischof** [comment] 2016-01-07 18:45
Yes. I can post the full output if needed.

**Comment by tdreyno** [comment] 2016-01-07 19:40
Yes please. Can you post your config and Gemfile.lock too

**Comment by lbischof** [comment] 2016-01-07 22:44
Error output: http://pastebin.com/qABmD35X

I just commented out everything from my config.rb except:
```
configure :development do                                                                                                                                            
  activate :livereload                                                                                                                                               
end
```
and deleted all helper files. This is my Gemfile:
```
source 'https://rubygems.org'
gem 'middleman'
gem 'middleman-livereload'

``` 
I ran `bundle update` and am on the latest versions. The problem still persists (I think the mutex warning is new). Happy to give more info if you need it.

**Comment by tdreyno** [comment] 2016-01-08 02:59
And removing `activate :livereload`, removes the message?

**Comment by lbischof** [comment] 2016-01-09 13:18
No removing livereload does not fix the bug.

**Comment by woodall** [comment] 2016-01-10 15:54
@lbischof any chance your project is public so I can test it locally?

**Comment by lbischof** [comment] 2016-01-10 18:12
[yeah sure](https://github.com/lbischof/maplesplendor.ca)

**Comment by cybernetlab** [comment] 2016-07-06 11:56
same issue when editing helpers:

```
E, [2016-07-06T14:53:10.314467 #17015] ERROR -- : run() in thread failed: stream closed:\n /home/user/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify/notifier.rb:300:in `readpartial'
```

**Comment by JTronLabs** [comment] 2016-08-28 15:31
same issue

**Comment by BigChief45** [comment] 2016-11-16 08:54
I have this same issue. Any solutions yet?

**Comment by sandstrom** [comment] 2016-12-25 22:38
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

Does this error occur in all environments (OS + ruby version), or just some?

A great start would be an example repo (based off a clean install) that exhibit this error.

**Comment by fxmountain** [comment] 2018-02-08 08:57
Same problem

**Comment by sandstrom** [comment] 2018-02-08 09:15
@fxmountain If you want to help fix this a great start would be an example repo (based off a clean install) that exhibit this error.

**Comment by fxmountain** [comment] 2018-03-19 05:56
Can't reproduce it any more, but also switched to 4.2.1

**Closed** 2021-09-24 09:47 UTC
Labels: wontfix
