### ISSUE TITLE
ignore parameter (:ignore => true) on proxy for dynamic pages gets ignored

### ISSUE THREAD

**Issue by crtvhd** [middleman/middleman#1556] opened 2015-07-10 12:26 UTC
I'm using `proxy` to generate pages based on yaml data, which works perfectly fine in DEV mode:

``` ruby
# config.rb
data.portfolio.projects.each do |p|
  proxy "/projects/#{p.client.name.parameterize}/#{p.title.parameterize}", "/projects/show.html", locals: { project: p }, ignore: true
end
```

However, during the build process, middleman tries to build `/projects/show/index.html` anyways, although I'm explicitly setting `ignore: true` as stated in the [docs](https://middlemanapp.com/advanced/dynamic_pages/):

``` console
# log
== Request: /projects/show/index.html
error  build/projects/show/index.html
undefined local variable or method `project' for #<#<Class:0x007fca30ddd1f8>:0x007fca315ddc90>
```

My workaround so far: Ignore the page manually after configuring the proxy

``` ruby
ignore "/projects/show.html"
```

Now the question: Did I misunderstand the purpose of `ignore: true` on `proxy` or is this option simply being ignored? I'm using middleman 4.0.0.beta.2.

**Comment by tdreyno** [comment] 2015-07-10 17:20
I've seen this recently. The tests pass, but this is definitely an issue. Thanks for logging.

**Comment by monfresh** [comment] 2015-10-17 23:43
I ran into this as well, and digging into the source code, I noticed that the tests do not include a scenario based on the documentation. If you add the following block to `middleman-core/fixtures/dynamic-pages-app/config.rb`:

```ruby
["tom", "dick", "harry"].each do |name|
  proxy "/about/#{name}.html", "/should_be_ignored9.html", :locals => { :person_name => name }, :ignore => true
end
```
and add `should_be_ignored9.html` to the list of files that should not exist in `features/dynamic_pages.feature`, the test will fail.

I suspect it has to do with the presence of the locals option, or perhaps the order in which it appears.

**Comment by monfresh** [comment] 2016-01-04 01:51
Hi. I'm still seeing this in version 4.0.0. What was the reason for closing this issue?

**Comment by tdreyno** [comment] 2016-01-04 19:10
Hmm, I know I wrote tests and fixed this... but then it's not in git. Must have been a failed push and I never realized it.

**Comment by shibulijack-fd** [comment] 2016-03-18 16:42
Any update on this issue? Build keeps failing!

**Comment by tdreyno** [comment] 2016-03-18 17:31
@shibulijack-fd which version of Middleman?

**Comment by shibulijack-fd** [comment] 2016-03-18 17:32
3.1.2.

**Comment by tdreyno** [comment] 2016-03-18 17:35
Try upgrading to v3.4.1 at least.

**Comment by shibulijack-fd** [comment] 2016-03-18 17:38
The problem is, we have been using middleman on a large project for almost over a year now and we have made a lot of customizations on it. So upgrading is not an option for us. Can you please point to the commit which addresses this issue, so that I could update those changes on our forked repo?

**Comment by shibulijack-fd** [comment] 2016-03-20 07:04
For those facing a similar issue, I fixed it temporarily by checking if the locals of the page has been defined.

`<% if !(defined?(YOUR_LOCAL_NAME)).nil?%>`

**Comment by tdreyno** [comment] 2016-03-20 23:13
Sorry, @shibulijack-fd, v3.1.2 is nearly 3 years old. I've got no idea which commit in the last 3 years solve d this particular issue. Glad you found a temporary fix.

**Comment by sandstrom** [comment] 2016-11-20 19:50
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! This should work in v4. If not a a PR with a failing test would be a great start.

**Closed** 2016-12-24 09:09 UTC

**Comment by johnnyshields** [comment] 2018-01-18 17:48
I'm still seeing this issue.
