### ISSUE TITLE
v4 Sass import error

### ISSUE THREAD

**Issue by drewbarontini** [middleman/middleman#1799] opened 2016-02-09 12:01 UTC
`Sass::SyntaxError: File to import not found or unreadable`

This is only happening in v4 and I'm not sure why. I'm just doing simple `@import 'directory/file'` imports like I have in any previous version. The `Gemfile.lock` lists out `compass-import-once`, so I assume that functionality should exist?

Not sure what's changed here. Any help is appreciated.

**Comment by drewbarontini** [comment] 2016-02-09 13:17
Figured it out. You have to have your `set :css_dir, 'assets/stylesheets'` inside of the `configure` block for the environment. I assumed you could set it outside of those and have it apply to all. Is there any way to do that?

**Comment by tdreyno** [comment] 2016-02-09 17:48
Are you saying that setting that at the root of config.rb doesn't work? Pretty sure we have tests covering that. Can you post your `config.rb`?

**Comment by drewbarontini** [comment] 2016-02-09 18:18
Yes, I had it like this:

```ruby
set :css_dir, 'assets/stylesheets'
set :js_dir, 'assets/javascripts'
set :images_dir, 'assets/images'
set :fonts_dir, 'assets/fonts'
```

And, to fix it, I changed it to:

```ruby
configure :development do
  set :css_dir, 'assets/stylesheets'
  set :js_dir, 'assets/javascripts'
  set :images_dir, 'assets/images'
  set :fonts_dir, 'assets/fonts'
end
```

**Comment by tdreyno** [comment] 2016-02-10 00:40
hmm, definitely a bug

**Comment by drewbarontini** [comment] 2016-02-10 19:54
Related: I'm also not able to just set general configuration variables anywhere in `config.rb`:

```ruby
set :example_url, 'http://www.example.com'
```

Adding this at the root or within an environment block yields the same `undefined local variable or method NameError`.

**Comment by tdreyno** [comment] 2016-02-10 21:09
That is incredibly weird, and possibly unique since I'm not getting a flood of bug reports. Can you share with me (privately if necessary) a repo I can reproduce this on?

**Comment by drewbarontini** [comment] 2016-02-11 12:01
It's a private repo, but I could drop in the entire `config.rb`, if that would help at all.

**Comment by tdreyno** [comment] 2016-02-13 04:02
That and Gemfile.lock would be great

**Comment by drewbarontini** [comment] 2016-02-13 12:59
`config.rb`

```ruby
# -------------------------------------
#   Layouts
# -------------------------------------

page '/*.xml', layout: false
page '/*.json', layout: false
page '/*.txt', layout: false

# -------------------------------------
#   Helpers
# -------------------------------------

helpers do
  # If you need helpers for use in this file, then you
  # can define them here. Otherwise, they should be defined
  # in `helpers/custom_helpers.rb`.
end

# -------------------------------------
#   Ignores
# -------------------------------------

ignore '/author.html'

# -------------------------------------
#   Author Pages
# -------------------------------------

data.authors.each do |author|
  author_slug = author[ :name ].downcase.strip.gsub( ' ', '-' ).gsub( /[^\w-]/, '' )
  proxy "author/#{ author_slug }", 'author.html', locals: { author: author[ :name ] }
end

# -------------------------------------
#   Blog Configuration
# -------------------------------------

activate :blog do |blog|
  blog.sources  = 'articles/{year}-{month}-{day}-{title}.html'
  blog.layout   = 'article'
  blog.paginate = true
  blog.per_page = 8

  blog.custom_collections = {
    category: {
      link: '/category/{category}.html',
      template: '/category.html'
    }
  }
end

# -------------------------------------
#   After Configuration
# -------------------------------------

after_configuration do
  @bower_config = JSON.parse( IO.read( "#{ root }/.bowerrc" ) )
  sprockets.append_path File.join root.to_s, @bower_config['directory']
end

# -------------------------------------
#   Development Configuration
# -------------------------------------

configure :development do

  set :css_dir, 'assets/stylesheets'
  set :js_dir, 'assets/javascripts'
  set :images_dir, 'assets/images'
  set :fonts_dir, 'assets/fonts'

  set :markdown_engine, :redcarpet
  set :markdown, :fenced_code_blocks => true, :smartypants => true
  set :haml, { ugly: true }

  activate :automatic_image_sizes
  activate :directory_indexes
  activate :livereload
  activate :syntax

  activate :autoprefixer do |config|
    config.browsers = ['last 2 versions', 'Explorer >= 10']
    config.cascade = false
  end

end

# -------------------------------------
#   Production Configuration
# -------------------------------------

 configure :production do

  set :css_dir, 'assets/stylesheets'
  set :js_dir, 'assets/javascripts'
  set :images_dir, 'assets/images'
  set :fonts_dir, 'assets/fonts'

 end

# -------------------------------------
#   Build Configuration
# -------------------------------------

configure :build do

  activate :asset_hash
  activate :minify_css
  activate :minify_html
  activate :minify_javascript
  activate :relative_assets

end
```

`Gemfile.lock`

```ruby
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.5.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    autoprefixer-rails (6.3.2)
      execjs
      json
    backports (3.6.8)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    chunky_png (1.3.5)
    coderay (1.1.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass (1.0.3)
      chunky_png (~> 1.2)
      compass-core (~> 1.0.2)
      compass-import-once (~> 1.0.5)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9)
      sass (>= 3.3.13, < 3.5)
    compass-core (1.0.3)
      multi_json (~> 1.0)
      sass (>= 3.3.0, < 3.5)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (0.9.2)
    contracts (0.12.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.0.9.1)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (1.8.1)
      addressable (~> 2.3, >= 2.3.5)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (2.0.0)
      concurrent-ruby (~> 0.8)
    hashie (3.4.3)
    htmlcompressor (0.2.0)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.9.0)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    method_source (0.8.2)
    middleman (4.1.1)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.1)
      middleman-core (= 4.1.1)
      sass (>= 3.4.0, < 4.0)
    middleman-autoprefixer (2.7.0)
      autoprefixer-rails (>= 6.3.1, < 7.0.0)
      middleman-core (>= 3.3.3)
    middleman-blog (4.0.0)
      addressable (~> 2.4.0)
      middleman-core (>= 4.0.0)
      tzinfo (>= 0.3.0)
    middleman-cli (4.1.1)
      thor (>= 0.17.0, < 2.0)
    middleman-compass (4.0.1)
      compass (>= 1.0.0, < 2.0.0)
      middleman-core (>= 4.0.0)
    middleman-core (4.1.1)
      activesupport (~> 4.2)
      addressable (~> 2.4.0)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.12.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 1.8)
      hamster (~> 2.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      tilt (~> 1.4.1)
      uglifier (~> 2.6)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-minify-html (3.4.1)
      htmlcompressor (~> 0.2.0)
      middleman-core (>= 3.2)
    middleman-sprockets (4.0.0.rc.1)
      middleman-core (>= 4.0.0.rc.1)
      sprockets (~> 3.0)
    middleman-syntax (2.1.0)
      middleman-core (>= 3.2)
      rouge (~> 1.0)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2015.1120)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    multi_json (1.11.2)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.1)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.1)
      tilt (~> 1.4.1)
    padrino-support (0.13.1)
      activesupport (>= 3.1)
    parallel (1.6.1)
    pry (0.10.3)
      coderay (~> 1.1.0)
      method_source (~> 0.8.1)
      slop (~> 3.4)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    redcarpet (3.3.4)
    rouge (1.10.1)
    sass (3.4.21)
    slop (3.6.0)
    sprockets (3.4.1)
      rack (> 1, < 3)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (2.7.2)
      execjs (>= 0.3.0)
      json (>= 1.8.0)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (>= 4.0.0)
  middleman-autoprefixer
  middleman-blog
  middleman-compass (>= 4.0.1)
  middleman-livereload
  middleman-minify-html
  middleman-sprockets (>= 4.0.0.rc.1)
  middleman-syntax
  pry
  redcarpet
  tzinfo-data
  wdm (~> 0.1.0)

BUNDLED WITH
   1.10.6
```

Let me know if you need anything else.

**Comment by Podlas29** [comment] 2016-08-16 17:28
Hi. I had very similar issue. sass imports where throwing errors (could not found some files). After setting css directory inside `configure` block, everything worked as a charm ;)

**Comment by chrishough** [comment] 2016-11-06 21:48
I have tried this work around and it is not working :(

```ruby
configure :development do
  set :css_dir, 'assets/stylesheets'
  set :js_dir, 'assets/javascripts'
  set :images_dir, 'assets/images'
  set :fonts_dir, 'assets/fonts'

  activate :livereload,
           host: '127.0.0.1',
           apply_js_live: false,
           apply_css_live: false
end

configure :production do
  set :css_dir, 'assets/stylesheets'
  set :js_dir, 'assets/javascripts'
  set :images_dir, 'assets/images'
  set :fonts_dir, 'assets/fonts'
end
```

**Comment by chrishough** [comment] 2016-11-06 21:56
The only way I was able to fix this was change the name of my `scss` files from `.css.scss` to just `.scss` as shown... 
<img width="192" alt="screen shot 2016-11-06 at 1 55 40 pm" src="https://cloud.githubusercontent.com/assets/744056/20042092/c1802070-a428-11e6-8819-deaf45a41c6d.png">

**Comment by sandstrom** [comment] 2016-12-25 22:52
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the middleman sprockets repo.

**Comment by andy-twosticks** [comment] 2017-07-01 17:13
Well ... that's disappointing.  

As a new Middleman user trying to get middleman working, could we have some explanation of HOW we use external pipelines to solve this problem?  I see literally nothing about how to do this in the documentation.  Hardly anything about SASS at all, actually.

I see the page on External Pipelines, and it has many examples, but none for SASS and no explanation of what the configuration options actually mean...

**Comment by iwarner** [comment] 2017-07-01 17:32
check out
https://github.com/iwarner/CodeBlender-Middleman

i use webpack for sass

**Comment by tdreyno** [comment] 2017-07-04 02:24
Hmm, seems like the `configure` issue is separate

**Comment by andy-twosticks** [comment] 2017-07-04 09:00
@iwarner 

I'm sorry, I know that you meant to be helpful, but you are suggesting that I replace external pipelines, a core Middleman feature with some documentation which I don't really understand enough to use, with an external library which I also don't know how to use and _has no documentation at all_?  

I'm not trying to be mean.  I wish I could say that that helped me, but I'm afraid it doesn't.

(Also, are you saying that external pipelines don't work? Why add an external dependency, otherwise?)

**Comment by sandstrom** [comment] 2017-07-04 11:52
Here are docs on the external pipeline: https://middlemanapp.com/advanced/external-pipeline/

It's not that hard, basically you just wire up some command line tool of your liking.

**Comment by iwarner** [comment] 2017-07-04 13:25
@andy-twosticks 

Hiya - seems you are a bit emotional about all of this :)

I was simply copying you my repository - I think the best way I have learnt middleman and indeed ruby is checking out other peoples repos. I dont think anywhere I say replace external pipelines or that they do not work....

In that codeblender repo I am using Webpack with SASS and Coffeescript - I believe the setup you require.

A google also - webpack middleman sass
reveals https://rossta.net/blog/using-webpack-with-middleman.html

Direct Link to webpack config
https://github.com/iwarner/CodeBlender-Middleman/blob/master/webpack.config.js

**Comment by andy-twosticks** [comment] 2017-07-04 15:30
@iwarner I don't know why you think I'm being emotional (or why you think emotion would be a bad thing, actually).  I was just feeding back to you. I'm afraid you are reading something into my text that was never there.  Once again: I'm sure you were trying to be helpful; thank you.  But I'm afraid your response was of no help to me.

@sandstrom: yes, I have of course read the documentation on External Pipelines. It gives some excellent examples, but since it doesn't really explain what the parameters of the config setting actually mean, I find that I can't create a pipeline that I don't have an example for.  Perhaps I just need to play with it more.  But it's a shame that the documentation doesn't go further.

**Comment by iwarner** [comment] 2017-07-04 15:34
@andy-twosticks 

Ok so you found my complete - working example of webpack no help??
And the link to a great article explaining setup that I followed

Fair enough.

**Comment by lulalala** [comment] 2018-03-13 06:42
Using 4.2.1, the default init comes with `.css.scss` file. It's `@import` could not locate referenced file. Renaming it from `.css.scss` fixed the issue.

@sandstrom Since fresh middleman projects do not use sprockets, and `@import` is purely a sass function, I don't think this is related to sprockets at all.

The easiest fix I think is just to follow @chrishough 's solution, by renaming the generated `.css.scss` file to `.scss`. 

@tdreyno what are your thoughts? or if you want, I can show you my repo so you can replicate the issue.

**Comment by Naokimi** [comment] 2019-08-27 07:24
I think I have same issue.

Built new template with middleman. Had error 
> Sass::SyntaxError: File to import not found or unreadable

That it couldn't import bourbon. So I renamed `main.css.scss` to `main.scss`. But now it doesn't import any css (even if I try to write directly on the file h1 color:red; nothing changes). Renaming the file to `main.css` implements the css changes, but of course @import won't work anymore

**Comment by logemann** [comment] 2019-11-30 12:43
Have the same issue. 

@import 'utils/_variables.scss';

doesnt work even though _variables.scss is right there in the utils folder. Tried without mentioning .scss in the import statement but with no luck either. No matter what i do, imports dont work.

Also tried all the "set" css folder stuff in the config.rb without any difference

**Comment by jkraemer** [comment] 2020-02-15 10:27
fwiw, I ran into the same problem and it disappeared when I removed the `minify_css` from my build configuration.

**Closed** 2021-07-24 19:42 UTC
Labels: wontfix
