### ISSUE TITLE
Haml::TempleEngine: Option :ugly is invalid warning on middleman build process

### ISSUE THREAD

**Issue by sibinx7** [middleman/middleman#2087] opened 2017-05-01 10:00 UTC
```
Haml::TempleEngine: Option :ugly is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid
Haml::TempleEngine: Option :ugly is invalid
Haml::TempleEngine: Option :outvar is invalid
Haml::TempleEngine: Option :context is invalid

```
This warning shows on middleman build process 

#### Versions 
   Ruby version: 2.4.1
   Haml 5
   Middleman 4.2

**Comment by joshukraine** [comment] 2017-05-05 18:09
I'm seeing the same warnings. `:ugly` is [no longer supported by haml](https://github.com/middleman/middlemanapp.com/pull/705), so you should just remove it from your `config.rb` file. I believe the other two (`:outvar` and `:context`) may be related to an issue with the [tilt gem](https://github.com/rtomayko/tilt/search?utf8=%E2%9C%93&q=outvar&type=), but not sure.

Lines 55 & 56 in Middleman's file renderer appear to be significant: https://github.com/middleman/middleman/blob/7c968b9572923fd0f7fb176ca8e52a91727adf84/middleman-core/lib/middleman-core/file_renderer.rb#L55

**Comment by joshukraine** [comment] 2017-05-06 06:50
@sibinx7 Why did you close the issue? I don't think the issue is fixed yet.

**Comment by Nakilon** [comment] 2017-05-21 09:15
I see it with the following Gemfile:
```
  sinatra (~> 1.4.8)
  sinatra-contrib
  haml
```

**Comment by USvER** [comment] 2017-06-06 22:04
Same issue for sinatra with haml
ruby 2.4.1

**Comment by oncomouse** [comment] 2017-06-09 21:21
This is because HAML 5.0 has very aggressive error checking on options. To turn off the messages, add `Haml::TempleEngine.disable_option_validator!` to your config.rb file

Source: https://stackoverflow.com/questions/43934383/middleman-4-0-0-with-haml-template-engine-gives-error-when-starting-with-server

**Comment by joshuamcginnis** [comment] 2017-06-15 19:17
How does one set the `Haml::TempleEngine.disable_option_validator!` for Sinatra apps?

**Closed** 2018-01-30 18:45 UTC

**Comment by elia** [comment] 2018-03-30 17:32
For anyone needing to patch an older middleman before 4.3 is published here's a quick patch that can work from config.rb:

```rb
::Haml::TempleEngine.define_options context: nil
::HamlPatch ||= Module.new {
  # https://github.com/middleman/middleman/commit/02f95aa43980aac82455228aede681daf4fbb65c
  def evaluate(scope, locals, &block)
    options = {}.merge!(@options).merge!(filename: eval_file, line: line, context: @context || scope)
    if options.include?(:outvar)
      options[:buffer] = options.delete(:outvar)
      options[:save_buffer] = true
    end
    @engine = ::Haml::Engine.new(data, options)
    output = @engine.render(scope, locals, &block)
    output
  end
}
p patching_haml: ::HamlPatch

::Middleman::Renderers::HamlTemplate.prepend ::HamlPatch
```
