### ISSUE TITLE
Build fails with 4.1, relative_path_from error

### ISSUE THREAD

**Issue by annael** [middleman/middleman#1865] opened 2016-03-29 08:07 UTC
There is an issue building Middleman site (tried on ubuntu linux) and ruby 2.3.0, starting from version 4.1.0:

```
error  build/general-information/compliance/index.html
different prefix: "" and "/general-information/compliance"
/home/anna/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from'
```

No problems building with 4.0.0.

**Comment by tdreyno** [comment] 2016-03-29 16:42
Can you please share a reproducible test case? The contents of your config and `general-information/compliance/` will be necessary atleast.

**Comment by BinaryPaean** [comment] 2016-07-24 02:25
I get this as well, but on OSX.
```bash
/Users/aaronstewart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from': different prefix: "" and "/Users/aaronstewart/Documents/repos/pedestaldesigns.com/source" (ArgumentError)
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:57:in `initialize'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `new'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `block (2 levels) in manipulate_resource_list'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `map'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `block in manipulate_resource_list'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `manipulate_resource_list'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
	from /Users/aaronstewart/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/application.rb:308:in `initialize'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `new'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `block in build'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/activesupport-4.2.7/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:62:in `build'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/aaronstewart/Documents/repos/pedestaldesigns.com/vendor/bundle/ruby/2.3.0/gems/middleman-cli-4.1.10/bin/middleman:72:in `<top (required)>'
	from bin/middleman:17:in `load'
	from bin/middleman:17:in `<main>'
```

Gemfile:

```ruby
# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source "https://rubygems.org"

gem 'middleman', '~> 4.1.1'

gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-minify-html'
gem 'middleman-sprockets', "~> 4.0.0.rc"
gem 'font-awesome-middleman'
gem 'middleman-favicon-maker', '>= 4.0.1.beta.1'
gem 'middleman-compass'
gem 'bourbon'
gem 'neat'
gem 'bitters'

group :test do
	gem 'haml_lint'
	gem 'scss_lint'
end

gem 'rake'

# For faster file watcher updates on Windows:
# gem "wdm", "~> 0.1.0", :platforms => [:mswin, :mingw]
```

**Comment by danielbayerlein** [comment] 2016-08-16 14:44
Same problem here, since I have updated the dependencies.

<details>
  <summary>Gemfile</summary>
```ruby
source 'https://rubygems.org'

ruby '2.3.1'

gem 'middleman', '~> 4.1.10'
gem 'middleman-livereload', '~> 3.4.6'
gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
gem 'middleman-minify-html', '~> 3.4.1'
gem 'middleman-favicon-maker', '~> 4.0.4'
gem 'middleman-google-analytics', path: '../middleman-google-analytics'
```
</details>

<details>
  <summary> Gemfile.lock </summary>
```ruby
PATH
  remote: ../middleman-google-analytics
  specs:
    middleman-google-analytics (3.0.0)
      activesupport (~> 4.1)
      erubis
      middleman-core (>= 3.4)
      uglifier (>= 2.5, < 4.0)

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.7.1)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.2)
    contracts (0.13.0)
    docile (1.1.5)
    dotenv (2.1.1)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.7.0)
    fast_blank (1.0.0)
    fastimage (2.0.0)
      addressable (~> 2)
    favicon_maker (1.3.1)
      docile (~> 1.1)
    ffi (1.9.14)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.4)
    htmlcompressor (0.2.0)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.12.0)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    memoist (0.14.0)
    middleman (4.1.10)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.10)
      middleman-core (= 4.1.10)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.1.10)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.10)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      contracts (~> 0.13.0)
      dotenv
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0.0)
      memoist (~> 0.14)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      servolux
      tilt (~> 1.4.1)
      uglifier (~> 3.0)
    middleman-deploy (2.0.0.pre.alpha)
      middleman-core (>= 3.2)
      net-sftp
      ptools
    middleman-favicon-maker (4.0.4)
      favicon_maker (~> 1.3, >= 1.3.1)
      middleman-core (~> 4.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-minify-html (3.4.1)
      htmlcompressor (~> 0.2.0)
      middleman-core (>= 3.2)
    minitest (5.9.0)
    net-sftp (2.1.2)
      net-ssh (>= 2.6.5)
    net-ssh (3.2.0)
    padrino-helpers (0.13.2)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.2)
      tilt (>= 1.4.1, < 3)
    padrino-support (0.13.2)
      activesupport (>= 3.1)
    parallel (1.9.0)
    ptools (1.3.3)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    sass (3.4.22)
    servolux (0.12.0)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.1)
      execjs (>= 0.3.0, < 3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 4.1.10)
  middleman-deploy (~> 2.0.0.pre.alpha)
  middleman-favicon-maker (~> 4.0.4)
  middleman-google-analytics!
  middleman-livereload (~> 3.4.6)
  middleman-minify-html (~> 3.4.1)

RUBY VERSION
   ruby 2.3.1p112

BUNDLED WITH
   1.12.1
```
</details>

<details>
  <summary>Error</summary>
```bash
/Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/2.3.0/pathname.rb:520:in `relative_path_from': different prefix: "" and "/Users/danielbayerlein/Projects/bienenkind.de/source" (ArgumentError)
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/resource.rb:57:in `initialize'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `new'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:51:in `block (2 levels) in manipulate_resource_list'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `map'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:50:in `block in manipulate_resource_list'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-favicon-maker-4.0.4/lib/middleman-favicon-maker/extension.rb:49:in `manipulate_resource_list'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:234:in `block (4 levels) in ensure_resource_list_updated!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:232:in `block (3 levels) in ensure_resource_list_updated!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:231:in `block (2 levels) in ensure_resource_list_updated!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:224:in `block in ensure_resource_list_updated!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/2.3.0/monitor.rb:214:in `mon_synchronize'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/store.rb:221:in `ensure_resource_list_updated!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/sitemap/extensions/on_disk.rb:21:in `ready'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `block in execute'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:57:in `execute'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/application.rb:308:in `initialize'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `new'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:63:in `block in build'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.10/lib/middleman-core/util.rb:21:in `instrument'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/lib/middleman-cli/build.rb:62:in `build'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/group.rb:232:in `dispatch'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:40:in `block in register'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.10/bin/middleman:72:in `<top (required)>'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/bin/middleman:23:in `load'
	from /Users/danielbayerlein/.rbenv/versions/2.3.1/bin/middleman:23:in `<main>'
```
</details>

<details>
  <summary>Diff</summary>
```diff
diff --git a/Gemfile b/Gemfile
index 0ec2ea3..430d726 100644
--- a/Gemfile
+++ b/Gemfile
@@ -2,9 +2,9 @@ source 'https://rubygems.org'
 
 ruby '2.3.1'
 
-gem 'middleman', '~> 4.1.9'
+gem 'middleman', '~> 4.1.10'
 gem 'middleman-livereload', '~> 3.4.6'
 gem 'middleman-deploy', '~> 2.0.0.pre.alpha'
 gem 'middleman-minify-html', '~> 3.4.1'
-gem 'middleman-favicon-maker', '~> 4.0.3'
+gem 'middleman-favicon-maker', '~> 4.0.4'
 gem 'middleman-google-analytics', path: '../middleman-google-analytics'
diff --git a/Gemfile.lock b/Gemfile.lock
index a2cad14..8ef0941 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -10,7 +10,7 @@ PATH
 GEM
   remote: https://rubygems.org/
   specs:
-    activesupport (4.2.6)
+    activesupport (4.2.7.1)
       i18n (~> 0.7)
       json (~> 1.7, >= 1.7.7)
       minitest (~> 5.1)
@@ -39,7 +39,7 @@ GEM
       addressable (~> 2)
     favicon_maker (1.3.1)
       docile (~> 1.1)
-    ffi (1.9.10)
+    ffi (1.9.14)
     haml (4.0.7)
       tilt
     hamster (3.0.0)
@@ -49,22 +49,22 @@ GEM
     http_parser.rb (0.6.0)
     i18n (0.7.0)
     json (1.8.3)
-    kramdown (1.11.1)
+    kramdown (1.12.0)
     listen (3.0.8)
       rb-fsevent (~> 0.9, >= 0.9.4)
       rb-inotify (~> 0.9, >= 0.9.7)
     memoist (0.14.0)
-    middleman (4.1.9)
+    middleman (4.1.10)
       coffee-script (~> 2.2)
       compass-import-once (= 1.0.5)
       haml (>= 4.0.5)
       kramdown (~> 1.2)
-      middleman-cli (= 4.1.9)
-      middleman-core (= 4.1.9)
+      middleman-cli (= 4.1.10)
+      middleman-core (= 4.1.10)
       sass (>= 3.4.0, < 4.0)
-    middleman-cli (4.1.9)
+    middleman-cli (4.1.10)
       thor (>= 0.17.0, < 2.0)
-    middleman-core (4.1.9)
+    middleman-core (4.1.10)
       activesupport (~> 4.2)
       addressable (~> 2.3)
       backports (~> 3.6)
@@ -91,7 +91,7 @@ GEM
       middleman-core (>= 3.2)
       net-sftp
       ptools
-    middleman-favicon-maker (4.0.3)
+    middleman-favicon-maker (4.0.4)
       favicon_maker (~> 1.3, >= 1.3.1)
       middleman-core (~> 4.0)
     middleman-livereload (3.4.6)
@@ -126,16 +126,16 @@ GEM
     tilt (1.4.1)
     tzinfo (1.2.2)
       thread_safe (~> 0.1)
-    uglifier (3.0.0)
+    uglifier (3.0.1)
       execjs (>= 0.3.0, < 3)
 
 PLATFORMS
   ruby
 
 DEPENDENCIES
-  middleman (~> 4.1.9)
+  middleman (~> 4.1.10)
   middleman-deploy (~> 2.0.0.pre.alpha)
-  middleman-favicon-maker (~> 4.0.3)
+  middleman-favicon-maker (~> 4.0.4)
   middleman-google-analytics!
   middleman-livereload (~> 3.4.6)
   middleman-minify-html (~> 3.4.1)
```
</details>

**Comment by daveharrisonnet** [comment] 2016-10-13 14:10
do we have a fix for this yet?. I am up-to-date with all gems

**Comment by sandstrom** [comment] 2016-12-25 23:00
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test (a vanilla repo of a middleman site + the stuff needed for this failure to occur).

**Closed** 2016-12-26 13:33 UTC

**Comment by danielbayerlein** [comment] 2017-08-19 14:39
Fixed with https://github.com/follmann/middleman-favicon-maker/pull/45

**Comment by danielbayerlein** [comment] 2017-08-20 06:40
Please update `middleman-favicon-maker` to `4.0.5`.
