### ISSUE TITLE
middleman command fails: cannot load such file

### ISSUE THREAD

**Issue by AlexEscalante** [middleman/middleman#1859] opened 2016-03-24 09:03 UTC
I tried reinstalling middleman a couple of times, updating all my gems… any ideas? 

I am on OS X El Capitán. 

```
$ middleman
/Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `load': cannot load such file -- /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/bin/middleman (LoadError)
from /Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `<main>'
```

An excerpt from my gem list:

```
middleman (4.1.4)
middleman-blog (4.0.0, 3.2.0)
middleman-cli (4.1.4)
middleman-core (4.1.4, 3.1.6, 3.1.0)
middleman-more (3.1.6, 3.1.0)
middleman-sprockets (3.4.2, 3.1.4, 3.1.2)
```

**Comment by iwarner** [comment] 2016-03-24 12:52
try - $ bundle exec middleman server also

**Comment by tdreyno** [comment] 2016-03-24 17:03
Very weird. Maybe `rbenv rehash`? The Middleman command is not in the core gem, but the cli gem. Whatever links rbenv made are incorrect.

**Comment by AlexEscalante** [comment] 2016-03-24 20:15
@iwarner, I was not using a bundle, I just installed the gem and tried to use the CLI with no luck.

But let's try to create a bundle on some directory, with just the following:

    gem 'middleman

and then:

    $ bundle
     (...)
    Bundle complete! 1 Gemfile dependency, 44 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    
So, bundle is in place:

    $ bundle exec middleman init acme
    Bundler is using a binstub that was created for a different gem.
    This is deprecated, in future versions you may need to `bundle binstub middleman-core` to work around a system/bundle conflict.
         run  git clone --depth 1 git://github.com/middleman/middleman-templates-default.git /var/folders/8s/9p1rdd113vzc1zt7j63hkskc0000gn/T/d20160324-51146-6vma7 from "."
    Cloning into '/var/folders/8s/9p1rdd113vzc1zt7j63hkskc0000gn/T/d20160324-51146-6vma7'...
    remote: Counting objects: 22, done.
    remote: Compressing objects: 100% (15/15), done.
    remote: Total 22 (delta 0), reused 14 (delta 0), pack-reused 0
    Receiving objects: 100% (22/22), 6.07 KiB | 0 bytes/s, done.
    Checking connectivity... done.
       exist
      create  .gitignore
      create  Gemfile
      create  config.rb
      create  source/images/middleman-logo.svg
      create  source/index.html.erb
      create  source/javascripts/all.js
      create  source/layouts/layout.erb
      create  source/stylesheets/_normalize.scss
      create  source/stylesheets/site.css.scss
    Do you want to use Compass? y
    Do you want to use LiveReload? y
      insert  Gemfile
      insert  Gemfile
      insert  config.rb
      insert  Gemfile
    Do you want a Rack-compatible config.ru file? y
      create  config.ru
         run  bundle install from "./acme"

    (...)

    Bundle complete! 1 Gemfile dependency, 44 gems now installed.
    Use `bundle show [gemname]` to see where a bundled gem is installed.
    
Seems to have worked, let's go into the project dir and run bundle again:

    $ cd acme
    $ bundle
    (..)
    Bundle complete! 5 Gemfile dependencies, 54 gems now installed.

So far, so good, let's build:

    $ bundle exec middleman build
    Bundler is using a binstub that was created for a different gem.
    This is deprecated, in future versions you may need to `bundle binstub middleman-core` to work  around a system/bundle conflict.
      create  build/stylesheets/site.css
      create  build/javascripts/all.js
      create  build/images/middleman-logo.svg
      create  build/index.html
    Project built successfully.

So, I would say it's a success, but still I shouldn't need to create a directory and put a Gemfile inside to make it work, so this needs to be looked into.

**Now**: maybe this problem belongs to someone else but, when I try to use this template, I still have no luck:

    $ bundle exec middleman init acme --template=axyz/middleman-zurb-foundation
    $ bundle
    (...)
    An error occurred while installing eventmachine (1.0.3), and Bundler cannot continue.
    Make sure that `gem install eventmachine -v '1.0.3'` succeeds before bundling.

Ok, so, let's update everything to see if we can tie up things:

    $ bundle update
    (...)
    Bundle updated!

Ok, let's try building again:

    $ bundle exec middleman build
    Bundler is using a binstub that was created for a different gem.
    This is deprecated, in future versions you may need to `bundle binstub middleman-core` to work around a system/bundle conflict.
    /Users/alex/Devel/audelabs/test/acme/config.rb:5:in `evaluate_configuration!': undefined method  `compass_config' for #<Middleman::ConfigContext:0x007fa78454f280> (NoMethodError)
	from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:327:in `instance_eval'
	from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:327:in `evaluate_configuration!'
	from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-core-4.1.4/lib/middleman-core/application.rb:284:in `initialize'
	from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.4/bin/middleman:48:in `new'
	from /Users/alex/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/middleman-cli-4.1.4/bin/middleman:48:in `<top (required)>'
	from /Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `load'
	from /Users/alex/.rbenv/versions/2.2.2/bin/middleman:23:in `<main>'


So, I am still not where I would like to be, I will file a report on the right project…

Thanks!

**Comment by tdreyno** [comment] 2016-03-25 17:14
That event machine error often comes from now having compiler tools installed. If you google it, there should be a bunch of OS-specific fixes. Usually, `xcode-select --install` for OS X

**Comment by xavdid** [comment] 2016-07-09 08:11
FWIW, I was getting the same error using rvm installed ruby 2.3.0. I installed 2.2.5 and re-bundled and everything worked like a charm

**Comment by joallard** [comment] 2016-07-26 17:53
Confirming for Ruby 2.3.1, using Rbenv, running `middleman init foo` outside of a bundled dir.

```rb
# .rbenv/versions/2.3.1/bin/middleman
# last lines, L22-23:

gem 'middleman-core', version
load Gem.bin_path('middleman-core', 'middleman', version)
```

I can probably `mkdir` and make a Gemfile and then run Middleman, but that kinda defeats the purpose of `init`, does it? Maybe this is a Rubygems thing? I'm not exactly familiar with the way bins are linked to the right gems.

**Comment by davidsilvasmith** [comment] 2016-09-06 09:53
I have the same issue.
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis 
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

`middleman init`

```
~/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `load': cannot load such file -- ~/.rvm/gems/ruby-2.3.1/gems/middleman-core-4.1.10/bin/middleman (LoadError)
	from ~/.rvm/gems/ruby-2.3.1/bin/middleman:23:in `<main>'
	from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from ~/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by davidsilvasmith** [comment] 2016-09-06 10:03
Using @AlexEscalante 's work around when I `bundle exec middleman init sitename`

I get this output at the top

```
Bundler is using a binstub that was created for a different gem.
This is deprecated, in future versions you may need to `bundle binstub middleman-core` to work around a system/bundle conflict.
```
Maybe thats related?

I tried doing `bundle binstub middleman-core` and got 

```
middleman-core has no executables, but you may want one from a gem it depends on.
  bundler has: bundle, bundler
  rack has: rackup
  tilt has: tilt
  erubis has: erubis
  dotenv has: dotenv
  listen has: listen
  sass has: sass, sass-convert, scss
```

**Comment by trejster** [comment] 2016-09-23 12:27
Is there a fix for this? I have the same issue with rub 2.3.1

**Comment by tdreyno** [comment] 2016-09-26 18:17
Looks like a rbenv issue from this vantage point.

**Comment by renatocarvalho** [comment] 2016-10-12 22:45
I was having the same issue. Applying @joallard solution solved my issue.

I removed all middleman gems and installed again. That did the trick \o/

**Comment by passatgt** [comment] 2016-10-21 12:24
`gem install middleman-cli` solved the issue for me
an older middleman gem changed it to an older version and that caused the issue

**Comment by sandstrom** [comment] 2016-12-25 23:00
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I think things are working as intended, and that this issue can be closed. Feel free to disagree and if so a PR with a failing test plus a fix would be a great start.

**Closed** 2016-12-26 13:33 UTC

**Comment by andreamoro** [comment] 2017-03-28 18:26
Not sure whether a full answer was found from the OP and whether the above relates to it. But back last year I had a bunch of similar issues recently on Sierra. 

Ended up to be a mess between the gems and the default ruby version. For whatever reason they were messing up despite the which command and the path were pointing correctly to the latest ruby build.

Ended up cleaning all the gem references from my local users with something like
rm -rf /Users/username/.gem/ruby/2.0.0 

And then run again a bundle update / install.
