### ISSUE TITLE
Infinite loop when encountering files with the same name as a possible templating engine (e.g. markdown.scss)

### ISSUE THREAD

**Issue by patbenatar** [middleman/middleman#1889] opened 2016-04-21 22:12 UTC
`$ bundle exec middleman` hangs with no output. 

When I force quit it, I get the following stacktrace:

```
c^C/Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:59:in `tilt_recognizes?': Interrupt
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:65:in `step_through_extensions'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:98:in `collect_extensions'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:117:in `block in find_related_files'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:117:in `each'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:117:in `flat_map'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/util/files.rb:117:in `find_related_files'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:262:in `update'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources/source_watcher.rb:204:in `poll_once!'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `block in poll_once!'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `each'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `reduce'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/sources.rb:239:in `poll_once!'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/core_extensions/file_watcher.rb:50:in `before_configuration'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `instance_exec'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `block in execute'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `each'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:1316:in `traverse_depth_first'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/hamster-3.0.0/lib/hamster/vector.rb:431:in `each'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:57:in `execute'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_reference.rb:43:in `send_to'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/call_with.rb:76:in `call_with'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/contracts-0.13.0/lib/contracts/method_handler.rb:138:in `block in redefine_method'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/callback_manager.rb:28:in `block in install_methods!'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-core-4.1.7/lib/middleman-core/application.rb:282:in `initialize'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.7/bin/middleman:48:in `new'
        from /Users/me/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/middleman-cli-4.1.7/bin/middleman:48:in `<top (required)>'
        from /Users/me/.rbenv/versions/2.3.0/bin/middleman:23:in `load'
        from /Users/me/.rbenv/versions/2.3.0/bin/middleman:23:in `<main>'
```

My `Gemfile.lock` is:

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.1)
    contracts (0.13.0)
    erubis (2.7.0)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (2.0.0)
      addressable (~> 2)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.3)
    i18n (0.7.0)
    json (1.8.3)
    kramdown (1.10.0)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    middleman (4.1.7)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.7)
      middleman-core (= 4.1.7)
      sass (>= 3.4.0, < 4.0)
    middleman-cli (4.1.7)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.7)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.13.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      servolux
      tilt (~> 1.4.1)
      uglifier (~> 3.0)
    middleman-sprockets (4.0.0.rc.2)
      middleman-core (~> 4.0)
      sprockets (>= 3.0)
    mime-types (1.25.1)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.1)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.1)
      tilt (~> 1.4.1)
    padrino-support (0.13.1)
      activesupport (>= 3.1)
    parallel (1.8.0)
    rack (1.6.4)
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    sass (3.4.22)
    servolux (0.12.0)
    sprockets (3.6.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    xpath (2.0.0)
      nokogiri (~> 1.3)

PLATFORMS
  ruby

DEPENDENCIES
  middleman (~> 4.1, >= 4.1.7)
  middleman-sprockets (~> 4.0.0.rc)

BUNDLED WITH
   1.11.2
```

And I emptied out my `config.rb` to see if anything in there was causing issues, but still won't boot with no custom configuration.

**Comment by tdreyno** [comment] 2016-04-21 23:16
Can you try Ruby 2.2?

**Comment by patbenatar** [comment] 2016-04-22 17:55
@tdreyno absolutely. Just tried 2.2.0 and having the same issue... same stacktrace when force quitting it as well.

Let me know if there's anything I can do to help.

**Comment by tdreyno** [comment] 2016-04-22 22:56
Anything interesting about your environment? Docker? Vagrant? Network file system? Dropbox?

Does disabling sprockets have any effect?

Are there any large, nested directories in your project (node_modules, bower_components, etc)

**Comment by patbenatar** [comment] 2016-04-23 15:38
@tdreyno Don't believe so. Running on OS X in a nested dir within home. No bower, npm, etc. It's a pretty basic Middleman app that compiles markdown to HTML pages.

Tried removing `middleman-sprockets` and having same issue.

With `middleman-sprockets` back in the Gemfile, I threw a debugger inside `middleman-core` to poke around. It appears that lib/middleman-core/util/files.rb:65 `while tilt_recognizes?(path)` is infinitely looping on the `path` value `"markdown"`. I had a scss file called `markdown.scss`, when renaming to `markdown.css` it prevents the infinite loop and middleman boots successfully. Perhaps this issue better belongs on `middleman-sprockets`?

**Comment by tdreyno** [comment] 2016-04-23 19:45
Oooooh, that sounds like a very good bug :)

Seems like it's looping because `markdown` is your file name, but it is also a possible templating engine. 

Is that file intended to be imported? Otherwise, I'd suspect the name to be `markdown.css.scss`

I'll take a look.

**Comment by patbenatar** [comment] 2016-04-24 16:49
@tdreyno correct, it's being imported.

Interesting bug indeed! Let me edit this issue title to be more descriptive now that we've narrowed it down. I'll write a regression test if I have some time.

**Comment by patbenatar** [comment] 2016-04-24 18:06
@tdreyno Also, forgot to mention: confirmed that if I rename the file to `anything_else.scss`, it works. I have a regression test in place here: https://github.com/patbenatar/middleman/commit/27e0ab1e3e9b71439a6237c0d48a131584557290

**Comment by tdreyno** [comment] 2016-04-24 23:59
Would love if you could PR that test. I'll fix this tomorrow

**Comment by sandstrom** [comment] 2016-12-25 23:02
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the [middleman sprockets repo](https://github.com/middleman/middleman-sprockets/).

**Closed** 2016-12-26 13:32 UTC

**Comment by patbenatar** [comment] 2017-01-03 00:42
@sandstrom not challenging your decision to close — it's your prerogative — but I do want to note that the issue seemed to exist in `Middleman::Util.step_through_extensions` not Sprockets.

**Comment by sandstrom** [comment] 2017-01-03 08:58
@patbenatar When the number of issues is too high it becomes tricky to get an overview: which ones remain, which ones are edge-cases, etc. By closing old issues and asking people to re-open if the issue remain is often a good move.

In this case it seems like the issue is ready resolved by https://github.com/middleman/middleman/commit/8a8ee768ac3fa88f0bc995459d11d644ba40bbff, right?

**Comment by patbenatar** [comment] 2017-01-05 16:32
@sandstrom :+1: — I had totally forgotten that we merged a fix a while back.

**Comment by sandstrom** [comment] 2017-01-05 16:43
@patbenatar Great! No worries, it's easy to forget — I do all the time 😄
