### ISSUE TITLE
Middleman server and Google Maps JavaScript API not working together

### ISSUE THREAD

**Issue by tirdadc** [middleman/middleman#1944] opened 2016-06-23 14:17 UTC
I have a React component that leverages the [Google Maps JS autocomplete functionality](https://developers.google.com/maps/documentation/javascript/examples/places-autocomplete-addressform), and it works fine when I test it on the generated static site and in a Rails context.

I have noticed it not working consistently when I'm viewing the preview page provided by `middleman server`, and this with or without the `activate :livereload` setting. Is there anything in the server mode that would clash with external APIs?

**Comment by sandstrom** [comment] 2016-07-29 18:37
@tirdadc not really, middleman server is a server just as nginx or apache (albeit with a different purpose).

I've used Google Maps with middleman without any issues.

I'd suggest reposting this on StackOverflow, along with much more details on your issue (what's the error, preferably a code-snippet etc).

Feel free to close this issue since it's very likely not caused by middleman.

**Closed** 2021-07-25 00:40 UTC
Labels: wontfix
