### ISSUE TITLE
Config <=> Data problem, hacking on Middleman (upgrading to v4)

### ISSUE THREAD

**Issue by markets** [middleman/middleman#1868] opened 2016-04-03 13:22 UTC
Hi @tdreyno,

I'm building a little "framework" on top of Middleman. Actually, I'm trying to upgrade from v3.4 to v4.1.6 (last release) and I encountered something that breaks in v4, while was working on v3.

**Scenario**:

I have a collection under the `data` folder, I need to iterate over all elements inside, and use `proxy` to create a page for each one.

* config.rb (https://github.com/Subgin/tonic/blob/master/config.rb#L19)
  
  I'm delegating some config to a own module: `Tonic.run(self)`

* This module is placed under `lib/` (https://github.com/Subgin/tonic/blob/master/lib/tonic.rb) and I have some code like:

```
module Tonic
...
  def self.run(context) # context is passed as `self` from config
    context.data.collection.each do |item|
      context.proxy "/#{item.name}", "/templates/collection/detail.html", locals: { item: item }, ignore: true
    end
  end
...
end
```

This code works on v3, but breaks on v4. But it doesn't show any error on the terminal... If I add a debug line inside the each block (`puts "foo"`), it keeps printing the line, like an infinite loop ... and the server does not starts.

Master branch is using v3: https://github.com/Subgin/tonic/tree/master
I just pushed a v4 branch: https://github.com/Subgin/tonic/tree/mm4

Do you have any idea/advise? In v4 branch, I can place the loop inside the config.rb file and it works, just crashing when I delegate those settings to the module.

Thanks!

**Comment by tdreyno** [comment] 2016-04-08 20:37
I'm traveling, but can you see if renaming the set/file/variable from `collection` to something else fixes it. There is a new concept in v4 called `collection` and it may be interfering.

**Comment by markets** [comment] 2016-04-10 20:15
Hi @tdreyno,

Thanks a lot for your advice! I tried to rename the collection file, but I had no luck... I finally solved the issue by:

```ruby
#context.data.collection.each do |item|  # works on mm3
context.app.data.collection.each do |item| 
```

At this point (just in case):

```ruby
(byebug) context.class
Middleman::ConfigContext

(byebug) context.app.class
Middleman::Application
```

I'm not sure if those values (=> behaviour change) are expected from your side... by what I read, a lot of code has been refactored during MM4. I can make it work just by calling `context.app.data`, so we can close the issue from my side 👍 

PS I should review this new "collection" concept, after all, the tool I'm writing is exactly focused on collections...

**Comment by tdreyno** [comment] 2016-04-11 16:45
Ah, okay, I'm getting this. This is a "collections" issue.

Basically, what happens is anything using the `ConfigContext` and a handful of top-level values (like `data`) tries to save the calculations made, so they can be re-run if the data folder values changes.

Your example is pretty canonical (other than passing the context around). Let me dig in, might be a bug.

Collections are new and I'm not sure they are very heavily used (or documented yet) so this code could be a bit buggy right now. Would love to hear what you're building.

**Comment by tdreyno** [comment] 2016-04-11 17:14
Hmm, I can't reproduce off of github master. Can you try pointing your Gemfile there?

```
gem "middleman", github: "middleman/middleman"
```

**Comment by tdreyno** [comment] 2016-04-11 17:14
![tonic example 2016-04-11 10-14-46](https://cloud.githubusercontent.com/assets/233/14435744/39d92e40-ffce-11e5-90bc-20f96c6d6ec2.png)

**Comment by tdreyno** [comment] 2016-04-11 17:15
Oh, wait, n/m, you added your fix to the branch :-p

**Comment by tdreyno** [comment] 2016-04-11 17:22
Ah, okay, it's because it's mixing the config context and the collection context. Removing the `context.` before `proxy` also fixes it in v4 (and will allow it to update when data does).

```
module Tonic
...
  def self.run(context) # context is passed as `self` from config
    context.data.collection.each do |item|
      proxy "/#{item.name}", "/templates/collection/detail.html", locals: { item: item }, ignore: true
    end
  end
...
end
```

I'd suggest passing `data` or `data.collection` into your helper, rather than `self`.

I will also investigate whether this can be fixed on the MM side.

**Comment by markets** [comment] 2016-04-11 19:24
Hi @tdreyno, thanks a lot for that introspection!

I pushed all changes that I need to run on v4 here: https://github.com/Subgin/tonic/pull/10. 

I also tried to pass only the `data` object, but since the idea is to delegate all the config to a own class (things like: `context.helpers(Helpers)`)... I need to have access to all methods accessible in `config.rb`. The idea is to encapsulate all the MM integration and serve a simple `config.rb` file with just something like: `Tonic.run(self)`.

I tried your patch suggestion on mm4 branch:

```diff
diff --git a/lib/tonic.rb b/lib/tonic.rb
index f2b801d..304e251 100644
--- a/lib/tonic.rb
+++ b/lib/tonic.rb
@@ -5,8 +5,8 @@ module Tonic
   def self.run(context)
     context.helpers Helpers
 
-    context.app.data.collection.each do |item|
-      context.proxy "/#{item.name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')}", "/templates/collection/detail.html", locals: { item: item }, ignore: true
+    context.data.collection.each do |item|
+      proxy "/#{item.name.downcase.strip.gsub(' ', '-').gsub(/[^\w-]/, '')}", "/templates/collection/detail.html", locals: { item: item }, ignore: true
     end
   end
```

And it also works. With both patches, yours and this one https://github.com/Subgin/tonic/pull/10/commits/0d0995ac2bb810491e6a186e86dc601d37db96b4, the app works on v4, even the LiveReload feature.

Idea of `Tonic`: just drop a YAML (or JSON) with a collection of elements and have a site with auto-generated smart filtering and detail pages. I'm building this with @albertvp, on top of MM and vanilla JS. We're now discussing how will look the default theme and finishing some details, actually we can say is quite Alpha, just a prototype to iterate over a real example.

**Comment by tdreyno** [comment] 2016-04-11 20:11
Cool. Working to make what worked in v3 work in v4... I think I know how

**Comment by tdreyno** [comment] 2016-04-11 23:23
Okay, @markets, point at github master and the original should work

**Closed** 2016-04-11 23:23 UTC

**Comment by markets** [comment] 2016-04-12 08:12
hey @tdreyno, will do during the day and come back to you with info, thanks man! 🙇

**Comment by markets** [comment] 2016-04-13 11:38
Hi @tdreyno, I just tried with MM master branch and the engine works reverting this change https://github.com/Subgin/tonic/pull/10/commits/0d0995ac2bb810491e6a186e86dc601d37db96b4. 

Awesome! thanks 👍 🔝

**Comment by tdreyno** [comment] 2016-04-13 15:33
awesome. I'll try to get a new gem out today
