### ISSUE TITLE
Nested slim template not yielding content 

### ISSUE THREAD

**Issue by richardjlyon** [middleman/middleman#1883] opened 2016-04-18 06:40 UTC
Per [instructions](https://middlemanapp.com/basics/layouts/):

config.rb:

```
activate :blog do |blog|
  blog.layout = 'article_layout'
end
```

article_layout.slim:

```
- wrap_layout :layout do
  article
    == yield
```

layout.slim:

```
doctype html
  html
    head
    body
      == yield
```

expect:

```
<html>
  <head></head>
  <body>
    <article>
       .... 
    </article>
  </body>
</html>
```

get:

```
<html>
  <head></head>
  <body></body>
</html>
```

**Comment by tdreyno** [comment] 2016-04-18 16:35
Does `= wrap_layout :layout do` work?

**Comment by ethikz** [comment] 2016-08-03 19:34
I can confirm it does not work.  I am running into the same issue

**Comment by ethikz** [comment] 2016-10-07 13:58
@tdreyno Any update on this?

**Comment by sandstrom** [comment] 2016-12-25 23:01
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation or at least a failing test.

**Comment by chris-rock** [comment] 2017-01-18 21:50
+1 this is annoying

**Comment by ethikz** [comment] 2017-02-07 01:40
@sandstrom @tdreyno I don't think another issue needs to be submitted, this is a consistent problem that is still outlined to be able to be one in the documentation.

We have given examples of configurations and how they still don't work.

I have since abandoned Middleman because of the lack of support for such a issue that can't and won't be addressed.

**Comment by sandstrom** [comment] 2017-02-07 12:03
@ethikz I'm sorry that you feel that way.

Middleman, like many other open source projects, is built by the community. There is no company behind it, paying for development.

So, the only guaranteed way of getting a problem solved is to solve it yourself.

In case you cannot (it happens to me quite often, that I know too little to solve an issue), the second-best option is usually to be positive and helpful. For example, by producing a failing test or a boiled-down reproduction of the issue.

It may feel good to complain, but it won't magically solve the issue.

**Comment by iwarner** [comment] 2017-02-07 13:37
I just left a message regards the blog - which is a core reason of using middleman. this has had no love in months from anyone - there are outstanding pull requests. 

So the community is helping but the core developers are not responding or adding the pull requests.

The community can only go so far, but requires communication or a roadmap of what to assist with.

@sandstrom Appreciate your Issue Gardening - maybe do this on the Blog module too please !

**Comment by ethikz** [comment] 2017-02-07 18:15
@sandstrom I'm not complaining other than simply the fact that whoever built this has built such an ability to allow it to do this.  While it does not work as explained, there is an expectation of better documentation or some sort of idea on how to get it working.

Now onto the comment @iwarner, I see 12 pull requests currently, sure some are failing but there has been no activity in months as stated by previous poster.

I'm not going to keep reiterating things said but going through threads and just saying Issue Gardening is not helpful either.

There is clearly someone in the community who built this who should be able to chime in and help which isn't happening.  Maybe the original developer didn't and someone contributed it but again there is no help in this matter.

Some of us, mainly myself aren't intelligent enough to figure this out since I'm not a ruby developer so even if I could figure it out would be fruitless due to the outstanding pull requests.

**Comment by tdreyno** [comment] 2017-02-08 19:16
I haven't used middleman-blog in years, so, it really falls on the users and companies invested in that specific plugin to continue the support. There have been multiple calls for assistance on the Twitter, and some have pitched in to help. But, basically, blog is a plugin and will always have less focus than the core (unless someone very invested in it were to step up).

Sorry that this has caused frustration.

**Comment by iwarner** [comment] 2017-02-08 19:24
@tdreyno Thanks for the reply

I think you should look at this page then - https://directory.middlemanapp.com/#/extensions/all and amend the plugins that are now not officially supported then !

When I look at this I would instantly feel that it comes under the supervision of the core team.

I also feel that you should take some responsibility in maintaining a developer subscription to these core modules, at least make a comment in good time on them. about the lack of progress.

Unfortunately I am still not a Ruby developer and a lot of this passes me by, but I love your product and have now used if for several years, I will try and drum some support up.

Can you please make a comment on the ReadMe of the blog, or make me an admin so we can start the process of recruiting some experienced community members to help maintain this code plugin.

**Comment by ethikz** [comment] 2017-02-09 14:23
I agree with @tdreyno and also agree a lot with @iwarner 

It is very disconcerting that on the core of middleman is a list of supported extensions with no activity.  I think it should be the job of the core team to reach out to these developers of these plugins and get updates about their status.

It is this sort of thing that makes it useful only for a handful of things like a static site, which it does great and I love it for it, so to use it for that I will but if blogging is needed I will need to suggest something else.

**Closed** 2021-07-24 22:42 UTC
Labels: wontfix
