### ISSUE TITLE
Slow build performance with 4.x

### ISSUE THREAD

**Issue by derpixeldan** [middleman/middleman#1885] opened 2016-04-19 08:21 UTC
We're running Middleman 3.4.0 on Ruby 2.1.3 for a project with around 7.000 files and it takes approximately 40 seconds to build. Running Middleman 4.1.7 on Ruby 2.3.0 takes 4 minutes and 40 seconds to build.

It has been like that with any 4.x release and I've tried to track down what's wrong, no errors, it's just slow.

**Comment by tdreyno** [comment] 2016-04-19 16:04
Can you please post your Gemfile.lock and config.rb

**Comment by derpixeldan** [comment] 2016-04-19 16:39
**config.rb:**
Time.zone = "Pacific Time (US & Canada)"
activate :blog do |blog|
  blog.prefix = "blog"
  blog.layout = "blog"
  blog.summary_separator = /READMORE/
  blog.paginate = true
end
activate :sprockets
page "blog/rss.xml", :layout => false
page "blog/feed.xml", :layout => false
page "blog/ios.xml", :layout => false
page "blog/osx.xml", :layout => false
page "blog/android.xml", :layout => false
page "blog/windowsphone.xml", :layout => false
page "/sitemap.xml", :layout => false
page "/index.html", :layout => :empty
page "/index", :layout => :empty
helpers do
  def is_page_active(tab)
    current_page.data.tab == tab ? { :class => 'active' } : {}
  end
end
set :css_dir, 'stylesheets'
set :js_dir, 'javascripts'
set :images_dir, 'images'
configure :development do
  page "/signinstate/index.html", :layout => :signinstate
end
configure :build do
  activate :minify_css
  activate :minify_javascript
  activate :relative_assets
end
set :markdown_engine, :redcarpet
set :markdown, :fenced_code_blocks => true, :smartypants => true

**Gemfile.lock:**
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.6)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    addressable (2.4.0)
    backports (3.6.8)
    builder (3.2.2)
    capybara (2.5.0)
      mime-types (>= 1.16)
      nokogiri (>= 1.3.3)
      rack (>= 1.0.0)
      rack-test (>= 0.5.4)
      xpath (~> 2.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.10.0)
    compass-import-once (1.0.5)
      sass (>= 3.2, < 3.5)
    concurrent-ruby (1.0.1)
    contracts (0.13.0)
    em-websocket (0.5.1)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0.6.0)
    erubis (2.7.0)
    eventmachine (1.2.0.1)
    execjs (2.6.0)
    fast_blank (1.0.0)
    fastimage (2.0.0)
      addressable (~> 2)
    ffi (1.9.10)
    haml (4.0.7)
      tilt
    hamster (3.0.0)
      concurrent-ruby (~> 1.0)
    hashie (3.4.3)
    http_parser.rb (0.6.0)
    i18n (0.7.0)
    jquery-middleman (3.1.2)
      thor (>= 0.14, < 2.0)
    json (1.8.3)
    kramdown (1.10.0)
    listen (3.0.6)
      rb-fsevent (>= 0.9.3)
      rb-inotify (>= 0.9.7)
    middleman (4.1.7)
      coffee-script (~> 2.2)
      compass-import-once (= 1.0.5)
      haml (>= 4.0.5)
      kramdown (~> 1.2)
      middleman-cli (= 4.1.7)
      middleman-core (= 4.1.7)
      sass (>= 3.4.0, < 4.0)
    middleman-blog (4.0.1)
      addressable (~> 2.3)
      middleman-core (>= 4.0.0)
      tzinfo (>= 0.3.0)
    middleman-cli (4.1.7)
      thor (>= 0.17.0, < 2.0)
    middleman-core (4.1.7)
      activesupport (~> 4.2)
      addressable (~> 2.3)
      backports (~> 3.6)
      bundler (~> 1.1)
      capybara (~> 2.5.0)
      contracts (~> 0.13.0)
      erubis
      execjs (~> 2.0)
      fast_blank
      fastimage (~> 2.0)
      hamster (~> 3.0)
      hashie (~> 3.4)
      i18n (~> 0.7.0)
      listen (~> 3.0)
      padrino-helpers (~> 0.13.0)
      parallel
      rack (>= 1.4.5, < 2.0)
      sass (>= 3.4)
      servolux
      tilt (~> 1.4.1)
      uglifier (~> 3.0)
    middleman-livereload (3.4.6)
      em-websocket (~> 0.5.1)
      middleman-core (>= 3.3)
      rack-livereload (~> 0.3.15)
    middleman-sprockets (4.0.0.rc.2)
      middleman-core (~> 4.0)
      sprockets (>= 3.0)
    mime-types (3.0)
      mime-types-data (~> 3.2015)
    mime-types-data (3.2016.0221)
    mini_portile2 (2.0.0)
    minitest (5.8.4)
    nokogiri (1.6.7.2)
      mini_portile2 (~> 2.0.0.rc2)
    padrino-helpers (0.13.1)
      i18n (~> 0.6, >= 0.6.7)
      padrino-support (= 0.13.1)
      tilt (~> 1.4.1)
    padrino-support (0.13.1)
      activesupport (>= 3.1)
    parallel (1.8.0)
    rack (1.6.4)
    rack-livereload (0.3.16)
      rack
    rack-test (0.6.3)
      rack (>= 1.0)
    rb-fsevent (0.9.7)
    rb-inotify (0.9.7)
      ffi (>= 0.5.0)
    redcarpet (3.3.4)
    sass (3.4.22)
    servolux (0.12.0)
    sprockets (3.6.0)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    thor (0.19.1)
    thread_safe (0.3.5)
    tilt (1.4.1)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)
    uglifier (3.0.0)
      execjs (>= 0.3.0, < 3)
    xpath (2.0.0)
      nokogiri (~> 1.3)
PLATFORMS
  ruby
DEPENDENCIES
  builder
  jquery-middleman
  middleman
  middleman-blog
  middleman-livereload
  middleman-sprockets (~> 4.0.0.rc.1)
  nokogiri
  redcarpet
BUNDLED WITH
   1.11.2

**Comment by tdreyno** [comment] 2016-04-19 17:46
Can you run `time bundle exec middleman build --instrument` and share the output?

The performance regressions are tending to be in blog and sprockets, so it's not surprising to see that you've got both activated.

**Comment by derpixeldan** [comment] 2016-04-19 18:18
Middleman 3:
real	0m47.535s
user	0m40.035s
sys	0m3.397s

Middleman 4:
real	3m25.421s
user	17m8.055s
sys	3m10.553s

The setup hasn't changed so it shouldn't be any slower or is it due to the asset pipeline changes?

**Comment by tdreyno** [comment] 2016-04-19 19:15
The Rails team made significant changes to the pipeline between their versions 2 and 3. 

The instrument flag should have printed a lot of timing info. Did that not work? If not, omit the "time" prefix and post the results. Thanks

**Comment by derpixeldan** [comment] 2016-04-20 13:20
Yes, all the timing info got printed, but it's 17,000 lines of data containing info I'm not allowed to share/publish. It takes between 250 and 600ms for a file to get rendered average probably something around 400. Are you looking for anythings specific?

**Comment by tdreyno** [comment] 2016-04-20 21:21
at the beginning there is a bunch of "manipulator" steps, I'd like to see what they say for `blog` and `sprockets` in terms of milliseconds spent.

**Comment by derpixeldan** [comment] 2016-04-21 12:35
Nothing that takes unusually long:

== Blog Sources: /blog/{year}-{month}-{day}-{title}.html (:prefix + :sources)
== Instrument (sitemap.manipulator): 746.703ms
{:name=>:sitemap_ondisk}
== Instrument (sitemap.manipulator): 103.87100000000001ms
{:name=>:sitemap_endpoint}
== Instrument (sitemap.manipulator): 102.924ms
{:name=>:sitemap_proxies}
== Instrument (sitemap.manipulator): 101.13600000000001ms
{:name=>:sitemap_redirects}
== Instrument (sitemap.manipulator): 103.27699999999999ms
{:name=>:sitemap_ignore}
== Instrument (sitemap.manipulator): 105.654ms
{:name=>:sitemap_import}
== Instrument (sitemap.manipulator): 197.30100000000002ms
{:name=>:routing}
== Instrument (sitemap.manipulator): 4213.54ms
{:name=>:front_matter}
== Instrument (sitemap.manipulator): 1999.5240000000001ms
{:name=>:blog_blog1_articles}
== Instrument (sitemap.manipulator): 132.009ms
{:name=>:blog_blog1_paginate}
== Instrument (sprockets.asset_lookup): 89.917ms
{:asset=>#<Middleman::Sprockets::Resource path=help/sdk/android/3.0.1/android-developer-docs.css>}
== Instrument (sprockets): 90.416ms
{:name=>"process_resource", :resource=>#<Middleman::Sitemap::Resource path=help/sdk/android/3.0.1/android-developer-docs.css>}
DEPRECATION WARNING on line 73 of /source/stylesheets/custom.css.scss: #{} interpolation near operators will be simplified
in a future version of Sass. To preserve the current behavior, use quotes:

  unquote("#{$prefix}#{$value}")

You can use the sass-convert command to automatically fix most cases.

== Instrument (sprockets.asset_lookup): 236.86599999999999ms
{:asset=>#<Middleman::Sprockets::Resource path=stylesheets/custom.css>}
== Instrument (sprockets): 237.524ms
{:name=>"process_resource", :resource=>#<Middleman::Sitemap::Resource path=stylesheets/custom.css>}
== Instrument (sprockets.asset_lookup): 64.626ms
{:asset=>#<Middleman::Sprockets::Resource path=stylesheets/flexgrid.css>}
== Instrument (sprockets): 65.192ms
{:name=>"process_resource", :resource=>#<Middleman::Sitemap::Resource path=stylesheets/flexgrid.css>}
== Instrument (sprockets): 1033.7620000000002ms
{:name=>"manipulator.sprockets_resources"}
== Instrument (sprockets): 34.325ms
{:name=>"manipulator.ignore_resources"}
== Instrument (sitemap.manipulator): 1183.624ms
{:name=>:sprockets}
== Instrument (sitemap.manipulator): 113.384ms
{:name=>:sitemap_move_files}
== Instrument (sitemap.manipulator): 105.69099999999999ms
{:name=>:collections}
== Instrument (sitemap.manipulator): 156.698ms
{:name=>:routing}
== Instrument (sitemap.update): 9366.78ms
{:reasons=>[:touched_file, :registered_new_manipulator_front_matter, :registered_new_manipulator_sitemap_ondisk, :registered_new_manipulator_sitemap_import, :registered_new_manipulator_sitemap_endpoint, :registered_new_manipulator_sitemap_proxies, :registered_new_manipulator_sitemap_redirects, :registered_new_manipulator_sitemap_move_files, :registered_new_manipulator_sitemap_ignore, :registered_new_manipulator_routing, :registered_new_manipulator_collections, :registered_new_manipulator_blog_blog1_articles, :registered_new_manipulator_blog_blog1_paginate, :registered_new_manipulator_sprockets]}
== Instrument (builder.setup): 15755.658000000001ms
{}
== Instrument (builder.queue): 1075.2630000000001ms
{}

Even with blog and sprockets disabled it's slow. It seems to be that the building of each file is slower in average then before.

**Comment by tdreyno** [comment] 2016-04-21 17:24
I'm a little surprised with the time taken by front matter, but it may be related to the sheer number of files you have.

A couple more questions, if you don't mind. Hard to intuit this without a direct test case :)

About how many files are generated?

What is the dominant templating engine (erb? redcarpet?)

What is the dominant file output type? HTML?

Does commenting out the `:build` block help? There is some per-file parsing that happens now which could add 20-30% to render times.

Side note, `*.xml` should have no layout by default in v4.

**Comment by derpixeldan** [comment] 2016-04-22 16:06
Sure thing, thanks for your effort so far :)

- Files generated 6.871 total
- Dominant templating engine is Haml, but we have documentation in plain html, no templating, which is over 4000 files already.
- 4979 `.html`, rest is mostly no extension, `.png` and `.css`
- without the `:build` block it's around 30s only which is about 80% faster, I figured that actually the `activate :minify_javascript` is causing the process to slow down

**Comment by tdreyno** [comment] 2016-04-22 17:21
I actually suspect it is the `relative_assets` feature. Can you try commenting that out?

**Comment by derpixeldan** [comment] 2016-04-22 18:25
I tried it a couple of times now and it's definitely the `:minify_javascript`

**Comment by tdreyno** [comment] 2016-04-22 20:49
interesting. What platform are you on, we could try putting a fast JS compiler in there.

**Comment by derpixeldan** [comment] 2016-04-25 19:19
We're all running on OS X 10.11.4 what changed regarding the JS compiler in 3.x?

**Comment by tdreyno** [comment] 2016-04-25 21:32
Nothing, but you might see if adding `therubyracer` gem to your Gemfile helps at all.

**Comment by tdreyno** [comment] 2016-04-25 21:46
So, if can dig in a little more. Does it seem like the minify js is causing every single request to take longer or just JS requests?

About how many JS files are in the project? Anything interesting about them (tons of small files? One massive file?)

**Comment by derpixeldan** [comment] 2016-04-26 10:29
Argh, `therubyracer` is such a shit show, every new Ruby or OS X version seems to break it though it fixes the slowness issue. It's like an anchor preventing projects from being updated. I'd prefer to not use it in combination with Middleman.

Right now it's just 70 JS files 65 of them with no more than 60 lines.

Interesting, running `:minify_javascript` is slowing down each request not only the JS ones.

**Comment by tdreyno** [comment] 2016-04-26 16:27
That is interesting (and pretty scary). I've been working on some perf things on `master`. Can you take a look at pointing your Gemfile there. Probably not a silver bullet, but might help.

I'll look into seeing if the way we're minifying JS is inherently slow. Here's a quick test. Let's use a compressor that doesn't open a JS runtime and see if the performance problems remain:

```

      module ::PassThrough
        def self.compress(data)
          data
        end
      end

      activate :minify_javascript, compressor: ::PassThrough
```

**Comment by derpixeldan** [comment] 2016-04-26 18:53
Pointing to `master` doesn't make a difference.

Using the compressor solves the issue (as `therubyracer` does).

**Comment by tdreyno** [comment] 2016-04-26 21:47
Ah, okay, so the issue is in spinning up the JS runtime. Let me see if Uglifier is doing that once for every file or sharing an environment.

Are you cool with Node being the JS runtime instead of rubyracer?

```
EXECJS_RUNTIME=Node bundle exec middleman build
```

Is that faster?

**Comment by tdreyno** [comment] 2016-04-26 21:49
Another question. Do you seen source map information at the bottom of the compiled JS? I _think_ that feature was added to Uglifier in their most recent version

**Comment by derpixeldan** [comment] 2016-04-28 18:50
Weird, with Node it's also slow.

I have doubled checked the compiled JS files but haven't found any additional information.

**Comment by sandstrom** [comment] 2016-12-25 23:01
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets, and this seems to stem from sprockets.

I'd suggest closing this issue, and if the problem resurfaces (or still exist) a new issue can be opened in the [middleman sprockets repo](https://github.com/middleman/middleman-sprockets/).

**Closed** 2016-12-26 13:33 UTC
