### ISSUE TITLE
ignore directive not working

### ISSUE THREAD

**Issue by pbougie** [middleman/middleman#1789] opened 2016-02-03 15:11 UTC
I have a simple `ignore` directive in `config.rb`:

```ruby
ignore '/javascripts/vendor/*'
```
The directive worked in Middleman 4 but does not in 4.1. Has something changed  or is this a bug?

**Comment by tdreyno** [comment] 2016-02-03 17:46
Definitely looks like a bug and there was some code changed around that. Will investigate.

**Comment by tdreyno** [comment] 2016-02-03 17:48
Hmm. Passes the tests for this and my naive test case locally. Can you shared a `config.rb`, `Gemfile` and explain what isn't working?

**Comment by pbougie** [comment] 2016-02-03 18:00
The project is a really simple SPA. Worked fine on Middleman 4. The `ignore` directives stopped working after `bundle update` to version 4.1. Here are the requested files. The site works fine but it's including a bunch of JavaScript files that are already getting bundled into a single file using Sprockets.

`config.rb`:
```ruby
set :css_dir, 'stylesheets'
set :images_dir, 'images'
set :js_dir, 'javascripts'
set :layout, false

activate :directory_indexes
activate :autoprefixer do |config|
  config.browsers = ['last 5 versions', 'Explorer >= 9']
  config.remove   = false
end

ignore '/javascripts/shared/*'
ignore '/javascripts/vendor/*'

configure :build do
  activate :minify_css
  activate :minify_javascript
end
```
`Gemfile`:
```ruby
source 'https://rubygems.org'
gem 'middleman', '~> 4'
gem 'middleman-sprockets', '~> 4.rc'
gem 'rake'
gem 'guard-middleman'
gem 'terminal-notifier'
gem 'terminal-notifier-guard'
gem 'middleman-autoprefixer'
```

**Comment by tdreyno** [comment] 2016-02-03 18:24
Can you post the build output before and after?

Also, could you try a recursive glob:

```
ignore '/javascripts/shared/**/*'
```

**Comment by pbougie** [comment] 2016-02-03 18:31
Here's the build output. I tried using the recursive glob but it didn't change anything.

```
$ bundle exec middleman build --verbose
== Activating: file_watcher
== Activating: front_matter
== Activating: data
== Activating: inline_url_rewriter
== Activating: sitemap_ondisk
== Activating: sitemap_import
== Activating: sitemap_endpoint
== Activating: sitemap_proxies
== Activating: sitemap_redirects
== Activating: sitemap_move_files
== Activating: sitemap_ignore
== Activating: external_helpers
== Activating: erb_renderer
== Activating: coffee_renderer
== Activating: haml_renderer
== Activating: sass_renderer
== Activating: markdown_renderer
== Failed Activation `liquid_renderer` : cannot load such file -- liquid
== Failed Activation `slim_renderer` : cannot load such file -- slim
== Failed Activation `less_renderer` : cannot load such file -- less
== Failed Activation `stylus_renderer` : cannot load such file -- stylus
== Activating: default_helpers
== Activating: lorem
== Activating: routing
== Activating: collections
== Activating: sprockets
== Change (#<Set: {:source}>): .htaccess
== Change (#<Set: {:source}>): apple-touch-icon.png
== Change (#<Set: {:source}>): favicon-32.png
== Change (#<Set: {:source}>): favicon.ico
== Change (#<Set: {:source}>): favicon.png
== Change (#<Set: {:source}>): favicon.svg
== Change (#<Set: {:source}>): humans.txt
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): javascripts/default.js
== Change (#<Set: {:source}>): javascripts/shared/footer.js
== Change (#<Set: {:source}>): javascripts/shared/parse_xml.js
== Change (#<Set: {:source}>): javascripts/shared/routing.js
== Change (#<Set: {:source}>): javascripts/shared/search.js
== Change (#<Set: {:source}>): javascripts/vendor/date.format.js
== Change (#<Set: {:source}>): javascripts/vendor/page.js
== Change (#<Set: {:source}>): javascripts/vendor/zepto.js
== Change (#<Set: {:source}>): layouts/_aside.erb
== Change (#<Set: {:source}>): layouts/_blank_refer.erb
== Change (#<Set: {:source}>): layouts/_footer.erb
== Change (#<Set: {:source}>): layouts/_header.erb
== Change (#<Set: {:source}>): robots.txt
== Change (#<Set: {:source}>): stylesheets/_base.sass
== Change (#<Set: {:source}>): stylesheets/_mixins.sass
== Change (#<Set: {:source}>): stylesheets/_resets.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_aside.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_footer.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_header.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_list.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_main.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_tabs.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_wrapper.sass
== Change (#<Set: {:source}>): stylesheets/default.css.sass
== Change (#<Set: {:source}>): stylesheets/vendor/_normalize.scss
== Rebuilding resource list
== Reading: Local config: config.rb
== Activating: directory_indexes
== Activating: autoprefixer
== Requesting resource list rebuilding: first_run_change_ignore
== Requesting resource list rebuilding: first_run_change_ignore
== Activating: minify_css
== Activating: minify_javascript
Loaded extensions:
== Extension: file_watcher
== Extension: front_matter
== Extension: data
== Extension: inline_url_rewriter
== Extension: sitemap_ondisk
== Extension: sitemap_import
== Extension: sitemap_endpoint
== Extension: sitemap_proxies
== Extension: sitemap_redirects
== Extension: sitemap_move_files
== Extension: sitemap_ignore
== Extension: external_helpers
== Extension: erb_renderer
== Extension: coffee_renderer
== Extension: haml_renderer
== Extension: sass_renderer
== Extension: markdown_renderer
== Extension: default_helpers
== Extension: lorem
== Extension: routing
== Extension: collections
== Extension: sprockets
== Extension: directory_indexes
== Extension: autoprefixer
== Extension: minify_css
== Extension: minify_javascript
== Change (#<Set: {:source}>): .htaccess
== Change (#<Set: {:source}>): apple-touch-icon.png
== Change (#<Set: {:source}>): favicon-32.png
== Change (#<Set: {:source}>): favicon.ico
== Change (#<Set: {:source}>): favicon.png
== Change (#<Set: {:source}>): favicon.svg
== Change (#<Set: {:source}>): humans.txt
== Change (#<Set: {:source}>): index.html.erb
== Change (#<Set: {:source}>): javascripts/default.js
== Change (#<Set: {:source}>): javascripts/shared/footer.js
== Change (#<Set: {:source}>): javascripts/shared/parse_xml.js
== Change (#<Set: {:source}>): javascripts/shared/routing.js
== Change (#<Set: {:source}>): javascripts/shared/search.js
== Change (#<Set: {:source}>): javascripts/vendor/date.format.js
== Change (#<Set: {:source}>): javascripts/vendor/page.js
== Change (#<Set: {:source}>): javascripts/vendor/zepto.js
== Change (#<Set: {:source}>): layouts/_aside.erb
== Change (#<Set: {:source}>): layouts/_blank_refer.erb
== Change (#<Set: {:source}>): layouts/_footer.erb
== Change (#<Set: {:source}>): layouts/_header.erb
== Change (#<Set: {:source}>): robots.txt
== Change (#<Set: {:source}>): stylesheets/_base.sass
== Change (#<Set: {:source}>): stylesheets/_mixins.sass
== Change (#<Set: {:source}>): stylesheets/_resets.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_aside.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_footer.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_header.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_list.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_main.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_tabs.sass
== Change (#<Set: {:source}>): stylesheets/blocks/_wrapper.sass
== Change (#<Set: {:source}>): stylesheets/default.css.sass
== Change (#<Set: {:source}>): stylesheets/vendor/_normalize.scss
== Rebuilding resource list
== Requesting resource list rebuilding: touched_file
== Requesting resource list rebuilding: registered_new_manipulator_front_matter
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ondisk
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_import
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_endpoint
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_proxies
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_redirects
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_move_files
== Requesting resource list rebuilding: registered_new_manipulator_sitemap_ignore
== Requesting resource list rebuilding: registered_new_manipulator_routing
== Requesting resource list rebuilding: registered_new_manipulator_collections
== Requesting resource list rebuilding: registered_new_manipulator_sprockets
== Requesting resource list rebuilding: registered_new_manipulator_directory_indexes
== Rebuilding resource list
== Running manipulator: sitemap_ondisk
== Running manipulator: sitemap_endpoint
== Running manipulator: sitemap_proxies
== Running manipulator: sitemap_redirects
== Running manipulator: sitemap_ignore
== Running manipulator: sitemap_import
== Running manipulator: routing
== Running manipulator: front_matter
== Running manipulator: sprockets
== Running manipulator: directory_indexes
== Running manipulator: sitemap_move_files
== Running manipulator: collections
== Prerendering CSS
== Request: /stylesheets/default.css
== Finishing Request: stylesheets/default.css (0.0s)
   identical  build/stylesheets/default.css
== Building files
   identical  build/apple-touch-icon.png
   identical  build/favicon.png
   identical  build/favicon-32.png
   identical  build/favicon.ico
== Request: /favicon.svg
== Finishing Request: favicon.svg (0.0s)
== Request: /javascripts/vendor/page.js
== Finishing Request: javascripts/vendor/page.js (0.0s)
   identical  build/favicon.svg
== Request: /javascripts/shared/search.js
== Finishing Request: javascripts/shared/search.js (0.0s)
== Request: /javascripts/vendor/date.format.js
== Finishing Request: javascripts/vendor/date.format.js (0.0s)
== Request: /javascripts/shared/routing.js
== Finishing Request: javascripts/shared/routing.js (0.0s)
== Request: /javascripts/shared/footer.js
== Finishing Request: javascripts/shared/footer.js (0.0s)
== Request: /javascripts/vendor/zepto.js
== Finishing Request: javascripts/vendor/zepto.js (0.0s)
== Request: /javascripts/shared/parse_xml.js
== Finishing Request: javascripts/shared/parse_xml.js (0.0s)
== Request: /javascripts/default.js
== Finishing Request: javascripts/default.js (0.0s)
   identical  build/javascripts/shared/search.js
   identical  build/javascripts/shared/routing.js
   identical  build/javascripts/shared/footer.js
   identical  build/javascripts/vendor/date.format.js
== Request: /robots.txt
== Finishing Request: robots.txt (0.0s)
   identical  build/robots.txt
== Request: /humans.txt
== Finishing Request: humans.txt (0.0s)
   identical  build/humans.txt
   identical  build/javascripts/shared/parse_xml.js
== Request: /index.html
== Finishing Request: index.html (0.02s)
   identical  build/index.html
== Request: /.htaccess
== Finishing Request: .htaccess (0.0s)
   identical  build/.htaccess
   identical  build/javascripts/vendor/page.js
   identical  build/javascripts/vendor/zepto.js
   identical  build/javascripts/default.js
Project built successfully.
```

**Comment by tdreyno** [comment] 2016-02-04 17:00
Thank you, I'll try to setup a test case today, unless you've got one available.

**Comment by pbougie** [comment] 2016-02-04 17:52
I've created a test case for you: https://github.com/pbougie/middleman-issue-1789

I noticed while building the test case that if I remove the middleman-sprockets gem, the `ignore` directive starts working again.

**Comment by tdreyno** [comment] 2016-02-04 21:39
Ah, great, another Sprockets bug. Pretty much why we're not really supporting it any more. I'll see if this is quickly fixable

**Comment by tdreyno** [comment] 2016-02-04 21:44
Looks like this may be fixed on git already. Try changing your Gemfile to:

```
gem 'middleman-sprockets', github: 'middleman/middleman-sprockets'
```

**Comment by pbougie** [comment] 2016-02-04 22:18
Unfortunately it did not fix the problem. I've made the change to the test case as well:
https://github.com/pbougie/middleman-issue-1789

**Comment by tdreyno** [comment] 2016-02-04 22:21
I get

```
thomasreynolds:middleman-issue-1789 thomasreynolds$ bundle exec middleman b
      create  build/stylesheets/default.css
      create  build/index.html
      create  build/javascripts/default.js
      create  build/javascripts/vendor/zepto.js
Project built successfully.
```

You?

**Comment by tdreyno** [comment] 2016-02-04 22:21
is it the vendor that's wrong?

**Comment by tdreyno** [comment] 2016-02-04 22:21
Ah, I see this is simplified from the above output post earlier. On it :)

**Comment by pbougie** [comment] 2016-02-04 22:23
This JavaScript file should be excluded:
`/javascripts/vendor/zepto.js`

Yes, the test case is very much simplified from the earlier post.

**Comment by sandstrom** [comment] 2016-03-15 18:42
In the process of updating to Middleman 4. Overall it's been pretty smooth, I like the new version.

However, I'm also seeing this issue. Did either of you manage to track it down?

**Comment by tdreyno** [comment] 2016-03-16 17:21
@sandstrom Can you confirm you're also using `middleman-sprockets`?

**Comment by sandstrom** [comment] 2016-03-16 19:15
@tdreyno Yes!

**Comment by stevenosloan** [comment] 2016-03-16 19:22
I'll add an issue and get working on that -- I think we should definitely be respecting ignore's.

**Comment by tdreyno** [comment] 2016-03-17 17:10
@stevenosloan Reach out if it's confusing. Basically, `ignore` run as a reducer pass and simply marks the resources as ignored (they can still be queried via the sitemap if necessary). We may simply need to re-run the ignore step after sprockets.

**Comment by stevenosloan** [comment] 2016-03-18 18:48
@pbougie / @sandstrom should be good now if y'all don't mind checking.

**Comment by sandstrom** [comment] 2016-03-19 18:57
@stevenosloan it works, thanks a lot! :smile:

**Closed** 2016-03-20 23:15 UTC

**Comment by andreamoro** [comment] 2019-03-10 12:23
@tdreyno @stevenosloan have been having this issue since a while. Have put together a test project on my machine to arrive to the conclusion that anything that is nested in a subfolder under source is not traversed.

Any chance to look at this?

**Comment by andreamoro** [comment] 2019-03-10 18:17
Actually, I spent more times in investigating, and it seems the problem is connected with the i18n gem. If a directory within what it was designated the template folder is used with the ignore, in this circumstance the ignore command doesn't work. 
In any other circumstance it works.

I'm not sure who can patch this, but it would be really useful.

**Comment by tdreyno** [comment] 2019-03-10 21:01
Please open a new ticket and provide your test repo.

**Comment by andreamoro** [comment] 2019-03-12 06:18
@tdreyno repo and ticket created. They are available [here](https://github.com/middleman/middleman/issues/2260)
