### ISSUE TITLE
Cannot pull data from yml file in data/ into table array

### ISSUE THREAD

**Issue by jms1989** [middleman/middleman#1644] opened 2015-10-20 18:26 UTC
Hello, I've run into a problem. I am trying to use a data array for a table on my page. I get a syntax error when I try to do it. I'm using haml for the syntax of my html files and yml for the data file.

`%table.table.table-striped`
`  %thead`
`    %tr`
`      %th List of Services`
`      %th Price`
`  %tbody`
`    - data.services.services.each do |service|`
`    %tr`
`      %td=service.item`
`      %td=service.price`

From: source/index.html.haml

`services:`
`- item: "Operating System Maintenance"`
`  price: "$20"`

From data/services.yml

The error I get or some variant if I move the "data" line around.
`
SyntaxError at /
/www/html/root/middleman/project2/source/index.html.haml:41: syntax error, unexpected keyword_ensure, expecting keyword_end /www/html/root/middleman/project2/source/index.html.haml:45: syntax error, unexpected end-of-input, expecting keyword_end end;end;end;end ^
`

Please help, I'd really like to utilize this feature.

**Comment by Arcovion** [comment] 2015-10-20 19:37
The lines under the each block must be indented. 
Closing as this is not a bug in Middleman, try stackoverflow.

**Closed by Arcovion** 2015-10-20 19:37 UTC

**Comment by jms1989** [comment] 2015-10-20 20:20
I know it needs to be indented, I just couldn't get github to keep it indented. I don't know how to properly post code on here. Other than that, do you know why it's not working based on that? it seems like it'd work,

**Comment by jms1989** [comment] 2015-10-20 20:28
Every line in my code is properly indented. I moved the data line back a couple spaces and the error changes to this. 

NoMethodError at /
undefined method `services' for #<Middleman::CoreExtensions::Data::DataStore:0xae34c70>

Ruby	/usr/local/rvm/gems/ruby-2.0.0-p247/gems/middleman-core-3.1.6/lib/middleman-core/core_extensions/data.rb: in method_missing, line 177
Web	GET fileserver/

**Comment by tdreyno** [comment] 2015-10-23 01:35
@jms1989 Can you upgrade to Middleman 3.4.0 please, looks like you are on a very old version.
