### ISSUE TITLE
Middleman CLI fails with "no implicit conversion of nil into String" error

### ISSUE THREAD

**Issue by vifreefly** [middleman/middleman#2251] opened 2019-01-31 16:59 UTC
## Steps to reproduce the problem (from a clean middleman installation)
Steps to reproduce are simple:

```
$ gem install middleman
$ middleman init my_blog
```

Getting following not informative and not user-friendly error:

```
$ middleman init my_blog

Traceback (most recent call last):
        5: from /home/bob/.rbenv/versions/2.6.0/bin/middleman:23:in `<main>'
        4: from /home/bob/.rbenv/versions/2.6.0/bin/middleman:23:in `load'
        3: from /home/bob/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.2/bin/middleman:10:in `<top (required)>'
        2: from /home/bob/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.2/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
        1: from /home/bob/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.2/lib/middleman-core/load_paths.rb:29:in `setup_bundler'
/home/bob/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.2/lib/middleman-core/load_paths.rb:29:in `exist?': no implicit conversion of nil into String (TypeError)
```

I have no idea what's the problem. Readme https://middlemanapp.com/basics/start-new-site/ clearly states that it should just work like `rails new my_app` but it didn't.

## Expected behavior and actual 
CLI should work as expected. It should't fail with nil error.

## Additional information
- Ruby version: 2.6.0
- Middleman version: 4.3.2
- OS version: Ubuntu 18.10

**Comment by vifreefly** [comment] 2019-01-31 17:31
Just checked on another machine (Ubuntu 18.04 server), works as expected.. Looks like there is some problem with my environment (I use rbenv on the machine where middleman fails).

**Comment by vifreefly** [comment] 2019-01-31 17:56
I just tried run middleman CLI in some another directory of filesystem - all works fine. For some reason, middleman CLI fails inside my development `~/code` directory.. Perhaps the problem with Rbenv, but I never had similar issue with any others gems

**Comment by tdreyno** [comment] 2019-01-31 19:32
Hmm, maybe there's something to do with bundler or git already existing in there?

**Comment by vifreefly** [comment] 2019-01-31 20:48
Not sure.. For now I just created the middleman in another directory and that did the work. Looks like problem solved, will close the issue. Thanks anyway

**Comment by cschiewek** [comment] 2019-05-29 15:41
FWIW, I get this error with Ruby 2.6.3 and middleman 4.3.4, on MacOS 10.14.  

I can replicate it pretty easily via
```
asdf install ruby 2.6.3
asdf local ruby 2.6.3
gem install middleman
asdf reshim ruby
middleman -v 
```
results in 
``` 
Traceback (most recent call last):
	5: from /Users/curtis/.asdf/installs/ruby/2.6.3/bin/middleman:23:in `<main>'
	4: from /Users/curtis/.asdf/installs/ruby/2.6.3/bin/middleman:23:in `load'
	3: from /Users/curtis/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-cli-4.3.4/bin/middleman:10:in `<top (required)>'
	2: from /Users/curtis/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:15:in `setup_load_paths'
	1: from /Users/curtis/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `setup_bundler'
/Users/curtis/.asdf/installs/ruby/2.6.3/lib/ruby/gems/2.6.0/gems/middleman-core-4.3.4/lib/middleman-core/load_paths.rb:29:in `exist?': no implicit conversion of nil into String (TypeError)
```

**Comment by tdreyno** [comment] 2019-05-29 16:55
What is `asdf`?

**Comment by cschiewek** [comment] 2019-05-29 17:27
`asdf` is a version manager.  https://asdf-vm.com

I figured out _part_ of the problem.  I had a file named `config.rb` in a parent directly.  I didn't realize that middleman traversed up all the parents. Is there a _reason_ middleman does this?  It seems incorrect (and brittle) to assume any `config.rb` file in any parent directory is a middleman config.

That being said, the passing non-existant env vars to `File.exists?` will always error out. So, in 4.3.4: 
```
    def setup_bundler
      if found_gemfile_root = findup('Gemfile', ENV['MM_ROOT'])
        ENV['BUNDLE_GEMFILE'] ||= File.join(found_gemfile_root, 'Gemfile')
      end

      unless File.exist?(ENV['BUNDLE_GEMFILE'])
        ENV['BUNDLE_GEMFILE'] = File.expand_path('../../../../Gemfile', __FILE__)
      end

      if File.exist?(ENV['BUNDLE_GEMFILE'])
        require 'bundler/setup'
        Bundler.require
      else
        raise "Couldn't find your Gemfile. Middleman projects require a Gemfile for specifying dependencies."
      end
    end
```
will always fail unless BUNDLE_GEMFILE env var exists.  This looks like it's fixed in master though.

**Comment by tdreyno** [comment] 2019-05-29 19:36
Ah, so the issue is that you are trying to use `middleman` outside of a project (to init?), but the location was secretly inside a project because there was `config.rb` in a parent folder?

w.r.t. that behavior, Bundler itself uses the approach of looking up the tree to find its config file.

So, I am going

**Closed** 2021-07-24 20:42 UTC
Labels: wontfix
