### ISSUE TITLE
Middleman4 ERB compilation problems

### ISSUE THREAD

**Issue by ndorfin** [middleman/middleman#1783] opened 2016-01-28 05:20 UTC
Hey,

**ERB issue 1:**

Config data is not available in ERBs when used in combination with JavaScript files. e.g. `test.js.erb` has the following code:

```
console.log('hello <%= "world #{config[:foo]}#{bar}" %>');
```

That triggers the following error:

```
throw Error("NameError: undefined local variable or method `config' for
#<#<Class:0x007fc047191d10>:0x007fc0474393b0>
(in /Users/shaun/Projects/ndorfin/middleman4-erb-bug/source/javascripts/test.js.erb:1:in `_evaluate_template')")
```

**ERB issue 2:**

If a Sass ERB is included as a Sass Import, the output Sass file is not found.

e.g. `test.scss.erb` called via `@import "test"` in the CSS manifest triggers the following error:

```
SyntaxError: File to import not found or unreadable: test
```

**Context**

In both cases, it's the ERB extension causing the problem. Having an ERB run through files before handing them over to Sass or CoffeeScript / JS is very useful - it would be a shame to lose this functionality :(

Check out: https://github.com/ndorfin/middleman4-erb-bug for my test cases and Gemfile

I'm using Ruby 2.3.0 on OSX 10.11.3, Middleman master branch, and middleman-sprockets @ 4.0.0.rc.1.

**Comment by tdreyno** [comment] 2016-01-28 08:04
Remove sprockets, it is no longer supported and causing these problems

**Comment by ndorfin** [comment] 2016-01-28 22:30
Thanks @tdreyno, I've removed middleman-sprockets.

Summary of problems now:

- JS manifests don't work anymore. `//= require` and `//= require_tree .` directives no longer recognised. Is there an alternative?
- `set` in `config.rb` no longer works, as per: #1768 - I assume this is because of Middleman 4 config changes?
- `.scss.erb` files are not imported by (S)CSS manifests and are therefore not available to the Sass compiler

Anyway, I've updated the test cases at https://github.com/ndorfin/middleman4-erb-bug - here's a screenshot:
![screen shot 2016-01-29 at 11 00 11 am](https://cloud.githubusercontent.com/assets/107569/12660356/34e9e116-c678-11e5-933b-2011d7b75b6d.png)

Thanks for your attention, time and help!

**Comment by tdreyno** [comment] 2016-01-30 00:50
Manifests are a feature of sprockets, so removing it cause bullet points 1 and 3. What's the issue with 2?

**Comment by ravasthi** [comment] 2016-01-30 09:34
Hi, I'd like to ask for a clarification.

So in order to make my `_syntax.scss.erb` compilation work, I should remove `middleman-sprockets`? But doing that will also remove the dependency on sprockets, which will make my JS manifests break. Is that a correct summary?

**Comment by tdreyno** [comment] 2016-01-30 19:47
You could use standard Middleman partials to accomplish the same effect as Sprockets manifest. So `app.js.erb` would `<%= partial "my-other-js" %>`.

I'm not sure, but I believe the same would work with Sass.

The above issues are definitely bugs in `middleman-sprockets`. If anyone were willing to support, maintain or fix the issues for that project, it would be appreciated. But for now, I am simply using `external_pipeline` along with node build tooling for JS.

Middleman v3 will continue to work as it always have if you need that older, better supported version of sprockets.

**Comment by sksea** [comment] 2016-02-23 17:43
@tdreyno Hey, thanks for your efforts on MM4. 

I'm running into the same problem as @ravasthi. Ideally, I'd like to pass variables from data files `(*.json)` to my sass partials `(_*.scss.erb)`. Not sure if the problem is with the sass engine shipped with MM4, or maybe I'm misunderstanding how sass works, but sass partials with the `.scss.erb` extension can't be `@imported` and throw the error `File to import not found or unreadable: <partial-name>`.

I tried renaming my site.css.scss to site.css.scss.erb, but then `@import` stops working altogether. You mentioned using standard Middleman partials; could you elaborate on how those work within the context of sass partials? Thanks

**Comment by tdreyno** [comment] 2016-02-23 18:42
`@import` is built into Sass and has no concept of Middleman, so it can't find the files you are looking for or run Erb on them. If you're using Erb, you might be able to use Middleman's dependency management using `partial` as suggested above.

**Comment by tdreyno** [comment] 2016-02-23 18:43
app.css.scss.erb

```
<%= partial "other-thing" %>

html { styles: here }
```

Where `_other-thing.scss.erb` is a neighbor to app

**Comment by sksea** [comment] 2016-02-23 19:29
Hrm, now simply nothing gets imported into my site.css. (I tried both app.css.scss.erb and site.css.scss.erb). Does anything look off?
![image](https://cloud.githubusercontent.com/assets/11454733/13263849/6e3626e4-da39-11e5-9504-7c99b5163a88.png)

![image](https://cloud.githubusercontent.com/assets/11454733/13263924/d07ca90e-da39-11e5-9fb1-216cfea9192c.png)

**Comment by tdreyno** [comment] 2016-02-24 00:31
Seems reasonable. Really, no errors? Does the full path work: `partial "stylesheets/normalize"`?

**Comment by sksea** [comment] 2016-02-24 02:52
Sorry, realized it does build using `<%= partial "partial_name %>`. Maybe my browsersync proxy isn't configured correctly to work with middleman's server, but when I ran MM's server alone and looked on the default port 4567, site.css was getting compiled correctly. Thanks @tdreyno !

**Comment by tdreyno** [comment] 2016-02-24 04:57
@sksea Sorry for the inconvenience. It looks like MailChimp might pick up maintenance of our sprockets support, so maybe the future is bright

**Comment by sandstrom** [comment] 2016-07-24 17:08
For anyone else having issues around this, I got it working with this:

```scss
// all.css.scss.erb

<%= partial './_normalize.scss' %>

// rest of css…
```

and the other file being named `_normalize.scss` and being a sibling file to `all.css.scss`.

**Comment by banchee** [comment] 2016-10-29 14:52
Add this to your config.rb 

```
activate :sprockets do |c|
  c.expose_middleman_helpers = true
end

```

Found it on the middleman-sprockets github page.

**Comment by sandstrom** [comment] 2016-12-25 22:47
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue, and if the problem resurfaces a new issue can be opened.

**Closed** 2016-12-26 09:52 UTC
