### ISSUE TITLE
Swapping LiveReload with BrowserSync 

### ISSUE THREAD

**Issue by kevinSuttle** [middleman/middleman#1227] opened 2014-03-25 20:55 UTC
I've been using BrowserSync locally and I find it invaluable. Is it possible to not use middleman-livereload and use BrowserSync instead? I'm not sure how much work under the hood would be required given the asset pipeline and the async nature of BrowserSync, but I thought I'd ask anyway.

[browsersync.io](browsersync.io)

cc: @shakyshane

**Comment by stoplion** [comment] 2015-01-24 19:54
I run `browser-sync start --config bs-config.js` with MM. It works, but unfortunately it causes a full refresh (no style injection).

**Comment by andreimoment** [comment] 2015-03-08 22:18
@stoplion, do you run this in your build folder? Or do you somehow run it against your project? If the latter could you provide more details on your setup?

Thank you!

**Comment by marcinant** [comment] 2015-03-25 01:08
:+1:

**Comment by tdreyno** [comment] 2015-03-25 17:11
`middleman-livereload` is a plugin. If you don't want to use it, simply don't require or activate it. That said, would love to see a `middleman-browsersync` plugin.

**Comment by flexbox** [comment] 2015-05-18 20:00
@tdreyno Here is a clew 
https://gist.github.com/greypants/3590465cc1e9ad23d1c6
I don't know where to start to switch the asset pipeline, but it will be a good exercise.

**Comment by tdreyno** [comment] 2015-05-18 21:13
I'm using the `external_pipeline` feature of v4, which lets me run Webpack inside of Middleman.

**Comment by andreimoment** [comment] 2015-05-20 02:20
Would you consider sharing your set up?

**Comment by tdreyno** [comment] 2015-05-20 05:29
In config.

```
  activate :external_pipeline,
    name: :webpack,
    command: "cd frontend/ && #{build? ? './bin/build' : './bin/watch'}",
    source: "frontend/dist",
    latency: 2
```

Where `frontend` is a folder with a  npm/webpack setup. `build` simply calls `webpack -p` and `watch` calls `webpack --watch`.

Docs for this v4 stuff will be getting fleshed out as we approach launch.

**Comment by sebastianbarfurth** [comment] 2016-02-09 08:06
@tdreyno Doesn't really help with BrowserSync though, because it still can't quite get the rendered views. Of course if webpack compiles your stylesheets that is something BrowserSync can get, but not the views, since they're not compiled anywhere before build.

**Comment by svicalifornia** [comment] 2016-07-13 00:15
Any update on this issue? Is it possible to get the browser-synching benefits of BrowserSync to work from Middleman server?

**Comment by sandstrom** [comment] 2016-11-09 22:00
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Did the suggestion by @tdreyno work? I'd suggest closing this since this should work with external pipeline.

**Closed** 2016-11-19 21:34 UTC

**Comment by jescalan** [comment] 2017-09-08 18:40
Just checking here -- has anyone started work on a browsersync plugin at all? I'd be happy to try to help out if they have. The issue is not "closed" per-se, since external pipeline is not a viable solution for implementing browsersync since it will not pick up views as @sebastianbarfurth mentioned above.

**Comment by crstin** [comment] 2017-09-08 19:23
@jescalan Not sure if that helps, but I completely switched to using [https://github.com/vigetlabs/blendid](https://github.com/vigetlabs/blendid) and had no issues with live reloading since. IMHO it's a perfect fit as build system. You can see a little outdated introduction here: [https://www.youtube.com/watch?v=-io8EeB3GHI](https://www.youtube.com/watch?v=-io8EeB3GHI)

**Comment by jescalan** [comment] 2017-09-08 19:40
So it's not an issue with live reloading specifically that I have, I'm after some of the specific features of browsersync. But thank you for the recommendation!

**Comment by tdreyno** [comment] 2017-09-11 22:50
@jescalan Would love a community browsersync plugin. Middleman emits change events, so it should be possible to implement. See the live reload plugin for an example.
