### ISSUE TITLE
Editing config.rb while server is running and then exiting crashes Middleman

### ISSUE THREAD

**Issue by kasper** [middleman/middleman#1430] opened 2015-01-22 16:58 UTC
Editing config.rb while server is running and then exiting crashes Middleman 3.3.7 on Yosemite 10.10.1 and Ruby 2.2.0.

```
middleman-site $ bundle exec middleman
== The Middleman is loading
== The Middleman is standing watch at http://0.0.0.0:4567
== Inspect your site configuration at http://0.0.0.0:4567/__middleman/
== The Middleman is reloading
== The Middleman has reloaded
^C/Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:333:in `cleanup_shutdown_pipe': undefined method `each' for nil:NilClass (NoMethodError)
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:202:in `block in start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:32:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:162:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:36:in `block in start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:35:in `loop'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/preview_server.rb:35:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/cli/server.rb:78:in `server'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:72:in `method_missing'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:29:in `run'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:126:in `run'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/lib/middleman-core/cli.rb:20:in `start'
    from /Users/Kasper/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/middleman-core-3.3.7/bin/middleman:18:in `<top (required)>'
    from /Users/Kasper/.rbenv/versions/2.2.0/bin/middleman:23:in `load'
    from /Users/Kasper/.rbenv/versions/2.2.0/bin/middleman:23:in `<main>'
```

**Comment by tdreyno** [comment] 2015-01-22 19:42
Thanks for reporting

**Comment by alex88** [comment] 2015-01-23 11:09
I'm running a different but maybe related issue, when saving `config.rb` and running `middleman server --verbose` I get:

```
== The Middleman is standing watch at http://0.0.0.0:4567
== Inspect your site configuration at http://0.0.0.0:4567/__middleman/
[2015-01-23 12:07:35] INFO  WEBrick::HTTPServer#start: pid=25315 port=4567
[2015-01-23 12:07:39] INFO  going to shutdown ...
[2015-01-23 12:07:39] INFO  WEBrick::HTTPServer#start done.
== The Middleman is reloading
== Activating: sprockets
== Reading:  Local config
== Activating: gzip
== Activating: s3_sync
== Activating: blog
== Activating: livereload
Loaded extensions:
== Extension: sprockets
== Extension: gzip
== Extension: s3_sync
== Extension: blog
== Extension: livereload
== Extension: frontmatter
== File Change: circle.yml
......... removed due verbosity ...........
== File Change: source/works.haml
== Rebuilding resource list
== The Middleman has reloaded
[2015-01-23 12:07:39] INFO  WEBrick::HTTPServer#start: pid=25315 port=4567
[2015-01-23 12:07:39] ERROR NoMethodError: undefined method `[]' for nil:NilClass
	/usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:174:in `block in start'
== LiveReload accepting connections from http://192.168.0.150:35729
[2015-01-23 12:07:39] ERROR NoMethodError: undefined method `[]' for nil:NilClass
	/usr/local/var/rbenv/versions/2.2.0/lib/ruby/2.2.0/webrick/server.rb:174:in `block in start'
```

and goes on with the undefined method error continuously

**Comment by kasper** [comment] 2015-01-23 11:16
@alex88 I’m seeing that also for example when changing livereload settings while the server is running. See https://github.com/middleman/middleman-livereload/issues/71#issuecomment-71171266.

**Comment by alex88** [comment] 2015-01-23 11:22
@kasper I got that issue even without changing them, just by saving the `config.rb` file without changes

**Comment by kasper** [comment] 2015-01-23 11:28
@alex88 Yes, that also is enough.

**Comment by alex88** [comment] 2015-01-23 11:38
Well I've just tried without the livereload activated and the issue is the same

**Comment by tdreyno** [comment] 2015-01-23 21:56
Yeah, I think something may have changed slightly with Webrick... will investigate.

**Comment by nhemsley** [comment] 2015-03-08 17:23
This PR fixes the problem by stopping the webrick instance & recreating one on reload.

Probably wrong, but it may give someone with more of a clue why this is happening. 

The PR has more info why this bug is happening.

**Comment by alex88** [comment] 2015-03-24 09:25
@tdreyno when will you release the version with this fix?

**Comment by tdreyno** [comment] 2015-03-24 16:12
There was no change. As per: https://github.com/middleman/middleman/pull/1475#issuecomment-78118933 this was a bug in Ruby 2.2.0 which is fixed here (https://github.com/ruby/ruby/commit/ab0a64e1c87d8fd9d0a6ee8bb6bc084d0a6f482b) 

I guess we're waiting for Ruby 2.2.2

**Comment by alex88** [comment] 2015-03-24 16:20
Oh great, I misread the comment and I thought you merged the fix

**Comment by ashlynbaum** [comment] 2015-05-11 02:08
I'm using `2.2.2` and I still have the bug.

**Comment by tdreyno** [comment] 2015-05-11 16:24
@ashlynbaum Can you point your Gemfile at Github `v3-stable` branch? Let me know if it's fixed now.

**Comment by ashlynbaum** [comment] 2015-05-15 02:51
@tdreyno That did fix the bug, thanks.

**Comment by nhemsley** [comment] 2015-05-15 06:47
@tdreyno works for me.

**Comment by RickMeijer** [comment] 2015-07-16 09:13
Just an FYI for people coming in via Google:
Fixed in 3.3.13, which was yanked from rubygems.org. So you need to point to the repo in your Gemfile (gem 'middleman', github: 'middleman/middleman', branch: 'v3-stable').

**Comment by johnrlive** [comment] 2015-08-11 00:17
I commented out the following and the error went away. Not sure why, anyone care enough to explain?

#require 'rubygems'
#require 'middleman/rack'
#run Middleman.server

**Comment by sandstrom** [comment] 2016-11-09 22:15
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

This should be fixed and the issue can be closed.

**Closed** 2016-11-19 21:36 UTC
