### ISSUE TITLE
image_tag not working with asset_hash activated ... 

### ISSUE THREAD

**Issue by wgpubs** [middleman/middleman#1503] opened 2015-04-25 01:25 UTC
I have this in my index.slim:

=image_tag 'logo.png', :class => 'logo center-block img-responsive'

And in my config.rg, under "configure :build do:" ...

activate :asset_hash, :exts => ['.css', '.png', '.jpg', '.gif']

After builed, the image filenames are appropriately modified (e.g. logo.png becomes logo.png-539b9bbc.png), BUT the HTML produced by the "image_tag" in my slim template still points to the original named image:

img class="logo center-block img-responsive" src="images/ohmeow.png"

What am I missing?  Could this be a slim issue???

**Comment by tdreyno** [comment] 2015-04-25 17:14
No sure, could you share the code with me? I can look and see.

**Comment by wgpubs** [comment] 2015-04-25 17:55
Did some testing this morning.

The problem:  :asset_hash and image_tag do not work when using SLIM


The problem is *only* for pages built in slim.  If I use ERB (e.g.
index.html.erb) the "image_tag" helper works properly and the image name is
replaced with the cache-friendly name it is given fomr "activate
asset_hash".

However, if I use SLIM (e.g. index.slim or index.html.slim), the
"image_tag" isn't updated at all and it sitll references the original
filename.


-wg

**Comment by tdreyno** [comment] 2015-04-26 16:14
Thanks for the research @wgpubs, I'll add a slim specific test and see where that leads.

**Comment by tdreyno** [comment] 2015-04-26 16:43
Added some tests which pass. Can you post your `config.rb` and the actual portion of the slim template causing issues?

**Comment by wgpubs** [comment] 2015-04-27 16:27
After hearing that your slim tests passed I got curious about an option I
set in my config.rb to suppress "Slim:Engine: Option :lang is invalid"
warnings (see
https://github.com/middleman/middleman/issues/612#issuecomment-53827620):

Slim::Engine.disable_option_validator!


Anyhow, with this set, image_tag wasn't being updated to the cache-friendly
name of the image.  Interestingly enough, helpers like stylesheet_tag and
javascript_tag worked fine ... it is just image_tag.  I would seem to me
that those things should break as well.


Thanks for your assistance ... lmk what comes of it.

-wg

**Comment by tdreyno** [comment] 2015-04-27 16:50
If you're able to create a small test case app, I'm happy to debug. Otherwise, I'm afraid I can't reproduce this. Closing for now, but let me know if you're able to make the test case.

**Comment by kennethkalmer** [comment] 2015-05-06 22:42
I think I've figured out how to reliably replicate the issue, and I believe it is related to plasticine/middleman-imageoptim#32

Look at kennethkalmer/middleman-slim-images-asset-hash@7003bce5538 to see the commit that breaks the build. You need to **build twice**. On the second build, the hashes are stripped from the output.

`$ rm -rf build && middleman build && middleman build`

Inspect `build/index.html` and you'll see `middleman.png` instead of `middleman-50d9de35.png`

I hope this helps track down the issue, if there even is one. I got to this by helping @michelledasilva deploy a site with [shkm/middleman-neato](https://github.com/shkm/middleman-neato).

/cc @plasticine @kseyedmehdi @shkm

**Comment by sandstrom** [comment] 2016-12-25 22:32
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! I'd suggest either closing this issue or submitting a PR with an implementation as a starting point for discussion around this.

**Closed** 2016-12-26 09:49 UTC
