### ISSUE TITLE
activate :minify_css is partially stripping out asset_host.host string

### ISSUE THREAD

**Issue by nguyenj** [middleman/middleman#1784] opened 2016-01-28 20:52 UTC
```
# config.rb

activate :asset_hash,
  exts: %w(.jpg .jpeg .png .gif .js .css .hamljs .hamlc .eot .svg .ttf .woff .woff2)

activate :asset_host,
  host: "//cdn_id.cdn.com",
  exts: %w(.jpg .jpeg .png .gif .js .css .hamljs .hamlc .eot .svg .ttf .woff .woff2),
  sources: %w(.html .css)

activate :minify_css
```

```
# Un-minified stylesheet.css

@font-face{font-family:"some_font_name";
  src: url(//cdn_id.cdn.com/assets/some_font_name.eot);
  src: url(//cdn_id.cdn.com/assets/some_font_name.eot?#iefix) format("embedded-opentype"),
       url(//cdn_id.cdn.com/assets/some_font_name.woff) format("woff"),
       url(//cdn_id.cdn.com/assets/some_font_name.ttf) format("truetype"),
       url(//cdn_id.cdn.com/assets/some_font_name.svg#some_font_name) format("svg");
  font-weight:normal;
  font-style:normal
}
```

```
# Minified stylesheet.css

@font-face{font-family:"some_font_name";src:url(/assets/some_font_name.eot);src:url(//cdn_id.cdn.com/assets/some_font_name-d29f66df.eot?#iefix) format("embedded-opentype"),url(//cdn_id.cdn.com/assets/some_font_name.woff) format("woff"),url(//cdn_id.cdn.com/assets/some_font_name.ttf) format("truetype"),url(//cdn_id.cdn.com/assets/some_font_name.svg#some_font_name) format("svg");font-weight:normal;font-style:normal}
}
```

Not sure why when `activate :minify_css` is enabled, some of the font paths are prepended with the `asset_host.host` string and some are not.

**Comment by tdreyno** [comment] 2016-01-30 00:51
Okay, I'll add tests. Can you put minify at the top and see what happens?

**Comment by nguyenj** [comment] 2016-02-01 15:04
The same thing happens, I've just switched to using the external pipeline-thanks!

**Comment by tdreyno** [comment] 2016-02-01 18:06
May still be a bug worth fixing. Can you post your `Gemfile.lock`?

**Comment by nguyenj** [comment] 2016-02-02 00:05
```
# Gemfile

source "https://rubygems.org"

gem "coffee-script-source"
gem "middleman", "4.1.0.rc.2"
gem "middleman-sprockets", "~> 4.0.0.rc"
```

**Comment by tdreyno** [comment] 2016-02-02 00:14
Did the issue still happen without sprockets?

**Comment by nguyenj** [comment] 2016-02-02 02:08
Is there a way to load in external gem asset paths without using sprockets?

**Comment by tdreyno** [comment] 2016-02-02 18:14
`import_path`, but that only copies the files. It doesn't do inclusion like `//= require`

I'm just trying to narrow down the bug. If it only happens when sprockets is active, then I'll know.

You can also try pointing to the github `master` version of those gems to see if the issue is already fixed.

**Comment by bradgessler** [comment] 2016-03-10 02:30
Found a related issue in some much older code: https://github.com/middleman/middleman/issues/1024

**Comment by sandstrom** [comment] 2016-12-25 22:48
I'm doing some issue-gardening 🌿🌷🌾 and came across this issue.

Sorry that this has lingered for quite a while! With Middleman 4 the external pipeline is preferred method for assets. I'd suggest closing this issue, and if the problem resurfaces a new issue can be opened.

**Closed** 2016-12-26 09:52 UTC
