### ISSUE TITLE
Middleman 4: If Sass source file has .scss suffix (instead of .css.scss), compile file has no .css suffix

### ISSUE THREAD

**Issue by jimothyGator** [middleman/middleman#1676] opened 2015-11-05 21:08 UTC
In Middleman 3, a Sass file could be named (for example) either `site.css.scss` or `site.scss`. 

In Middleman 4, using the latter name results in a compiled file without the .css suffix. E.g., `build\stylesheets\site` instead of `build\stylesheets\site.css`.

While the obvious answer is to simply use the `.css.scss` suffix, it's worth nothing that in Rails 5/Sprockets 4, this suffix is no longer be supported, and was deprecated in Sprockets 3. The only supported suffix is `.scss`.

**Comment by jimothyGator** [comment] 2015-11-05 21:30
Tested against master branch and version 4.0.0.rc.1.

For master branch, middleman revision is ec99a7b28f6aa67ba33beb52e2d061138023823b. middleman-sprockets revision is 1177edb30c452211caca0a5751f59c1816320807.

**Comment by tdreyno** [comment] 2015-11-06 02:04
We've purposefully removed the `.scss` only version in v4... annoying to hear Sprockets has gone the other direction. We also support `.css.erb` and `.css.scss.erb`, so we need a concrete file type to output.

**Comment by tdreyno** [comment] 2015-11-11 20:27
Closing this as by design.

**Closed by tdreyno** 2015-11-11 20:27 UTC

**Comment by guzmaniglesias** [comment] 2016-02-01 15:28
Hey, any news about this issue? 
How this is compatible when using bower_components that contains .scss files?

**Comment by tdreyno** [comment] 2016-02-01 18:09
I think sass `@import` should still work for those.

**Comment by sandstrom** [comment] 2016-07-24 17:08
For anyone else having issues around this, I got it working with this:

```scss
// all.css.scss.erb

<%= partial './_normalize.scss' %>

// rest of css…
```

and the other file being named `_normalize.scss` and being a sibling file to `all.css.scss`.

**Comment by pomartel** [comment] 2018-03-25 21:31
Did anybody have  success running Middleman 4 with Sprockets 4? Sprockets 4 seems to ignore `.css.scss` file while Middleman expects the double extension. Not sure how to work this out!

**Comment by spinnylights** [comment] 2021-03-05 19:02
I want to note also that contemporary Sass's [`@use`](https://sass-lang.com/documentation/at-rules/use) and [`@import`](https://sass-lang.com/documentation/at-rules/import) rules, when passed e.g. `style`, will search for `style.scss`, `style.sass`, and `style.css`, but not `style.css.scss`. This suggests that Middleman has gone the opposite direction from upstream with its defaults. It's not that hard to work around, but I don't really understand what the rationale is behind this as a design choice.

**Comment by tdreyno** [comment] 2021-03-07 03:55
We allow the combination of any number of preprocessors and don't really care about the specifics of any of them. Our design allows:

style.css.erb
style.css.sass
style.css.scss.erb (variable injection)
style.css.less

etc, to all work then same. We've seen plenty of preprocessors come and go and choose to keep this part abstract to support all possible combinations.

**Comment by spinnylights** [comment] 2021-03-08 02:11
But I wouldn't say that supports all possible combinations of preprocessors. It's a graceful design to the extent that you can see the chain of preprocessors and the end result directly in the filename; at the same time, some preprocessors expect filenames to follow a set of conventions that clashes with this, so they may not be well-supported by that convention. I think it would be nice if this behavior was more configurable—it seems like a nice default but if this thread is any indication there are some users who aren't well-served by it. In theory I'd be happy to submit a patch we could discuss if y'all agree.

**Comment by tdreyno** [comment] 2021-03-08 02:42
I appreciate the offer. This feature did exist in Middleman 3 and was removed in favor of the more predictable approach in version 4. While I understand that it will still effect users who use this in combination with Sprockets, the reports of this issue have be quite rare over the years and I do believe the decision here was correct long term.

**Comment by spinnylights** [comment] 2021-03-08 02:58
Well, okay. I ran into this issue with Sass alone, moving over a pre-existing set of stylesheets—as you said you can get around it with @import and in this case that wasn't a big deal for me, but that may not work well for everybody. It's up to y'all, though.
